# -*- coding: utf-8 -*-
"""Final Plots

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Bq2JlxQyojIv1t-87j0hyD01GsjAXxK
"""

#Note: This should be run as a Jupyter notebook, and has been condensed into a Python file for simplicity. Cell boundaries have been indicated.

# %% [markdown]
# # Setup: Imports & Config

# %%
import os
import numpy as np
import matplotlib.pyplot as plt

DATA_DIR = "/mnt/beegfs/scoulombe"
BIN_NAMES = ["0", "1", "2"]

SNAPSHOT_TAG = "binned_finegrained_v2_bigmodel_n64_v1"          # original curriculum run's tag
FINETUNE_SNAPSHOT_TAG = "binned_finetune_flamingo_rot_v1"       # fine-tuning run's tag

# %% [markdown]
# ## Job key builders (QE / ViT expected keys)

# %%
# ---- one entry per job: (label, path, expected_keys) ----

def qe_keys(bin_names, eps_list, include_nl=True):
    keys = []
    for b in bin_names:
        for eps in eps_list:
            keys += [
                f"cl_true_bin{b}_eps{eps}",
                f"cl_qe_bin{b}_eps{eps}",
                f"cl_cross_bin{b}_eps{eps}",
                f"mse_bin{b}_eps{eps}",
                f"v_hat_bin{b}_eps{eps}",
            ]
            if include_nl:
                keys.append(f"Nl_bin{b}_eps{eps}")
    return keys

def vit_keys(bin_names, eps_list):
    keys = []
    for b in bin_names:
        keys.append(f"cl_true_bin{b}")  # saved once per bin, not per eps, in the ViT scripts
        for eps in eps_list:
            keys += [
                f"cl_vit_bin{b}_eps{eps}",
                f"cl_cross_bin{b}_eps{eps}",
                f"mse_bin{b}_eps{eps}",
                f"r2_bin{b}_eps{eps}",
                f"v_hat_bin{b}_eps{eps}",
            ]
    for eps in eps_list:
        keys += [
            f"loss_total_eps{eps}",
            f"loss_pixel_raw_eps{eps}",
            f"loss_patch_raw_eps{eps}",
            f"loss_spectral_raw_eps{eps}",
            f"loss_pixel_weighted_eps{eps}",
            f"loss_patch_weighted_eps{eps}",
            f"loss_spectral_weighted_eps{eps}",
        ]
    return keys

# %% [markdown]
# ## Job definitions (raw result files)

# %%
JOBS = [
    (
        "QE generated (l=10-5000)",
        os.path.join(DATA_DIR, "final_qe_generated", "qe_binned_results_l10-5000.npz"),
        qe_keys(BIN_NAMES, [0.0, 1.0]),
    ),
    (
        "QE flamingo (l=10-5000)",
        os.path.join(DATA_DIR, "final_qe_flamingo", "qe_binned_results_l10-5000_flamingo.npz"),
        qe_keys(BIN_NAMES, [0.0, 1.0]),
    ),
    (
        "QE nosignal (l=10-5000, eps=1.0 only)",
        os.path.join(DATA_DIR, "final_qe_nosignal", "qe_binned_results_l10-5000_nosignal.npz"),
        qe_keys(BIN_NAMES, [1.0]),
    ),
    (
        "ViT base/generated (stage 24)",
        os.path.join(DATA_DIR, "final_vit_base_generated", f"vit_results_base_generated_stage24_{SNAPSHOT_TAG}.npz"),
        vit_keys(BIN_NAMES, [0.0, 1.0]),
    ),
    (
        "ViT base/flamingo (stage 24)",
        os.path.join(DATA_DIR, "final_vit_base_flamingo", f"vit_results_base_flamingo_stage24_{SNAPSHOT_TAG}.npz"),
        vit_keys(BIN_NAMES, [0.0, 1.0]),
    ),
    (
        "ViT fine-tuned/flamingo (best checkpoint)",
        os.path.join(DATA_DIR, "final_vit_fine_flamingo", f"vit_results_finetuned_flamingo_{FINETUNE_SNAPSHOT_TAG}.npz"),
        vit_keys(BIN_NAMES, [0.0, 1.0]),
    ),
]

# %% [markdown]
# # Power spectrum ($C_\ell$) analysis
# ## $C_\ell$ job definitions

# %%
NSIDE = 2048
LMAX = 3*2048-1

ell = np.arange(LMAX+1)

CL_JOBS = [
    ("QE generated",            os.path.join(DATA_DIR, "final_qe_generated",  "qe_binned_results_l10-5000.npz"),
     "cl_qe",  True,  [0.0, 1.0]),
    ("QE flamingo",             os.path.join(DATA_DIR, "final_qe_flamingo",   "qe_binned_results_l10-5000_flamingo.npz"),
     "cl_qe",  True,  [0.0, 1.0]),
    ("QE nosignal",             os.path.join(DATA_DIR, "final_qe_nosignal",   "qe_binned_results_l10-5000_nosignal.npz"),
     "cl_qe",  True,  [1.0]),
    ("ViT base/generated",      os.path.join(DATA_DIR, "final_vit_base_generated", f"vit_results_base_generated_stage24_{SNAPSHOT_TAG}.npz"),
     "cl_vit", False, [0.0, 1.0]),
    ("ViT base/flamingo",       os.path.join(DATA_DIR, "final_vit_base_flamingo",  f"vit_results_base_flamingo_stage24_{SNAPSHOT_TAG}.npz"),
     "cl_vit", False, [0.0, 1.0]),
    ("ViT fine-tuned/flamingo", os.path.join(DATA_DIR, "final_vit_fine_flamingo",  f"vit_results_finetuned_flamingo_{FINETUNE_SNAPSHOT_TAG}.npz"),
     "cl_vit", False, [0.0, 1.0]),
]

# %% [markdown]
# ## Load $C_\ell$ data from files

# %%
cl_true_dict = {}
cl_pred_dict = {}
cl_cross_dict = {}

for label, path, pred_key_prefix, is_qe, eps_list in CL_JOBS:
    cl_true_dict[label] = {}
    cl_pred_dict[label] = {}
    cl_cross_dict[label] = {}
    with np.load(path) as d:
        for b in BIN_NAMES:
            cl_true_dict[label][b] = {}
            cl_pred_dict[label][b] = {}
            cl_cross_dict[label][b] = {}
            for eps in eps_list:
                if is_qe:
                    cl_true_dict[label][b][eps] = d[f"cl_true_bin{b}_eps{eps}"]
                else:
                    cl_true_dict[label][b][eps] = d[f"cl_true_bin{b}"]
                cl_pred_dict[label][b][eps] = d[f"{pred_key_prefix}_bin{b}_eps{eps}"]
                cl_cross_dict[label][b][eps] = d[f"cl_cross_bin{b}_eps{eps}"]

# %% [markdown]
# ## Bin the $C_\ell$ curves

# %%
BIN_WIDTH = 5  # ells 1-5, 6-10, 11-15, ...

def bin_cl_weighted(ell_in, cl_in, bin_edges, weights):
    binned = np.full(len(bin_edges) - 1, np.nan)
    for i in range(len(bin_edges) - 1):
        mask = (ell_in >= bin_edges[i]) & (ell_in < bin_edges[i + 1])
        if mask.sum() == 0:
            continue
        w = weights[mask]
        binned[i] = np.sum(w * cl_in[mask]) / np.sum(w)
    return binned

ell_min = 1
ell_max = ell.max()
n_bins = int(np.ceil((ell_max - ell_min + 1) / BIN_WIDTH))
bin_edges = ell_min + BIN_WIDTH * np.arange(n_bins + 1)
bin_centers = 0.5 * (bin_edges[:-1] + bin_edges[1:] - 1)

weights = 2 * ell + 1  # (2l+1), matching the equation

# %% [markdown]
# ## Apply binning

# %%
for label, path, pred_key_prefix, is_qe, eps_list in CL_JOBS:
    for b in BIN_NAMES:
        for eps in eps_list:
            cl_true_dict[label][b][eps] = bin_cl_weighted(ell, cl_true_dict[label][b][eps], bin_edges, weights)
            cl_pred_dict[label][b][eps] = bin_cl_weighted(ell, cl_pred_dict[label][b][eps], bin_edges, weights)
            cl_cross_dict[label][b][eps] = bin_cl_weighted(ell, cl_cross_dict[label][b][eps], bin_edges, weights)

ell = bin_centers

print(bin_edges)

# %% [markdown]
# ## Compute $r_\ell$ (cross-correlation coefficient)

# %%
r2_dict = {}

for label, path, pred_key_prefix, is_qe, eps_list in CL_JOBS:
    r2_dict[label] = {}
    for b in BIN_NAMES:
        r2_dict[label][b] = {}
        for eps in eps_list:
            cl_true = cl_true_dict[label][b][eps]
            cl_pred = cl_pred_dict[label][b][eps]
            cl_cross = cl_cross_dict[label][b][eps]
            r2_dict[label][b][eps] = cl_cross / np.sqrt(cl_true * cl_pred)

sum_weights_per_bin = bin_edges[1:]**2 - bin_edges[:-1]**2  # sum_{l in bin} (2l+1), closed form
# print(sum_weights_per_bin)

# %% [markdown]
# ## Plot: $r_\ell$ for generated data (QE vs ViT, eps=0 and 1)

# %%
for b in BIN_NAMES:
    fig, ax = plt.subplots(figsize=(9, 6))
    for eps in [0.0, 1.0]:
        if (eps == 1.0):
            cmb = "CMB"
        else:
            cmb = "no CMB"
        r2_qe = r2_dict["QE generated"][b][eps]
        err_qe = (1 - r2_qe**2) / np.sqrt(sum_weights_per_bin)
        qe_color = "darkorange" if eps == 0.0 else "tab:red"
        line_qe, = ax.plot(ell, r2_qe, label=f"QE {cmb}", color=qe_color)
        ax.fill_between(ell, r2_qe - err_qe, r2_qe + err_qe, color=line_qe.get_color(), alpha=0.2)

        r2_vit = r2_dict["ViT base/generated"][b][eps]
        err_vit = (1 - r2_vit**2) / np.sqrt(sum_weights_per_bin)
        vit_color = "indigo" if eps == 0.0 else "tab:blue"
        line_vit, = ax.plot(ell, r2_vit, label=f"ViT {cmb}", color=vit_color)
        ax.fill_between(ell, r2_vit - err_vit, r2_vit + err_vit, color=line_vit.get_color(), alpha=0.2)

    ax.set_xscale('log')
    # ax.set_yscale('log')
    ax.set_xlabel(r"$\ell$")
    ax.set_ylabel(r"$r_{\ell}$")
    ax.axhline(y=1, color="grey", linestyle="--")
    ax.set_ylim(0, 1.05)
    ax.legend()
    plt.tight_layout()
    plt.show()

# %% [markdown]
# ## Plot: $r_\ell$ for flamingo data, eps=0.0

# %%
for b in BIN_NAMES:
    fig, ax = plt.subplots(figsize=(9, 6))

    r2_qe = -r2_dict["QE flamingo"][b][0.0]
    err_qe = (1 - r2_qe**2) / np.sqrt(sum_weights_per_bin)
    line_qe, = ax.plot(ell, r2_qe, label="QE", color = "tab:red")
    ax.fill_between(ell, r2_qe - err_qe, r2_qe + err_qe, color=line_qe.get_color(), alpha=0.2)

    r2_base = -r2_dict["ViT base/flamingo"][b][0.0]
    err_base = (1 - r2_base**2) / np.sqrt(sum_weights_per_bin)
    line_base, = ax.plot(ell, r2_base, label="ViT Base", color = "tab:blue")
    ax.fill_between(ell, r2_base - err_base, r2_base + err_base, color=line_base.get_color(), alpha=0.2)

    r2_fine = r2_dict["ViT fine-tuned/flamingo"][b][0.0]
    err_fine = (1 - r2_fine**2) / np.sqrt(sum_weights_per_bin)
    line_fine, = ax.plot(ell, r2_fine, label="ViT Finetuned", color = "indigo")
    ax.fill_between(ell, r2_fine - err_fine, r2_fine + err_fine, color=line_fine.get_color(), alpha=0.2)

    ax.set_xscale('log')
    # ax.set_yscale('log')
    ax.set_xlabel(r"$\ell$")
    ax.set_ylabel(r"$r_{\ell}$")
    ax.axhline(y=1, color="grey", linestyle="--")
    ax.axhline(y=0, color="grey", linestyle="--")
    ax.set_ylim(-0.7, 1.05)
    ax.legend()
    plt.tight_layout()
    plt.show()

# %% [markdown]
# ## Plot: $r_\ell$ for flamingo data, eps=1.0

# %%
for b in BIN_NAMES:
    fig, ax = plt.subplots(figsize=(9, 6))

    r2_qe = -r2_dict["QE flamingo"][b][1.0]
    err_qe = (1 - r2_qe**2) / np.sqrt(sum_weights_per_bin)
    line_qe, = ax.plot(ell, r2_qe, label="QE", color = "tab:red")
    ax.fill_between(ell, r2_qe - err_qe, r2_qe + err_qe, color=line_qe.get_color(), alpha=0.2)

    r2_base = -r2_dict["ViT base/flamingo"][b][1.0]
    err_base = (1 - r2_base**2) / np.sqrt(sum_weights_per_bin)
    line_base, = ax.plot(ell, r2_base, label="ViT Base", color = "tab:blue")
    ax.fill_between(ell, r2_base - err_base, r2_base + err_base, color=line_base.get_color(), alpha=0.2)

    r2_fine = r2_dict["ViT fine-tuned/flamingo"][b][1.0]
    err_fine = (1 - r2_fine**2) / np.sqrt(sum_weights_per_bin)
    line_fine, = ax.plot(ell, r2_fine, label="ViT Finetuned", color = "indigo")
    ax.fill_between(ell, r2_fine - err_fine, r2_fine + err_fine, color=line_fine.get_color(), alpha=0.2)

    ax.set_xscale('log')
    # ax.set_yscale('log')
    ax.set_xlabel(r"$\ell$")
    ax.set_ylabel(r"$r_{\ell}$")
    ax.axhline(y=1, color="grey", linestyle="--")
    ax.axhline(y=0, color="grey", linestyle="--")
    ax.set_ylim(-0.7, 1.05)
    ax.legend()
    plt.tight_layout()
    plt.show()

# %% [markdown]
# # Mollweide + patch maps
# ## Imports & config

# %%
import healpy as hp
import matplotlib.pyplot as plt
import matplotlib.colorbar as mcolorbar
from matplotlib.colors import Normalize

DATA_DIR = "/mnt/beegfs/scoulombe"
BIN_NAMES = ["0", "1", "2"]
NSIDE_MAP = 2048
NSIDE_PATCH = 256

SMOOTHED_FILE = os.path.join(DATA_DIR, "final_mollweide_smoothed", "smoothed_maps_fwhm1deg.npz")

MOLLWEIDE_JOBS = {
    "generated": [
        ("QE generated",       None),
        ("ViT base/generated", None),
    ],
    "flamingo": [
        ("QE flamingo",             None),
        ("ViT base/flamingo",       None),
        ("ViT fine-tuned/flamingo", None),
    ],
}

EPS_LIST = [0.0, 1.0]
TITLE_MAP = {
    "QE generated": "QE",
    "ViT base/generated": "ViT",
    "QE flamingo": "QE",
    "ViT base/flamingo": "ViT Base",
    "ViT fine-tuned/flamingo": "ViT Finegrain",
}
PATCH_FACE, PATCH_ROW, PATCH_COL = 0, 0, 0

# %% [markdown]
# ## Layout constants (inches)

# %%
COL_WIDTH_IN     = 4.2   # width of each column (mollweide + patch share this)
MOLL_ASPECT      = 0.5   # mollweide height/width ratio (2:1 projection)
TITLE_PAD_IN     = 0.4   # extra room above the ellipse for the title
GAP_IN           = 0.35  # vertical gap between mollweide and patch
CBAR_PAD_IN      = 0.15  # gap between patch and its colorbar
CBAR_HEIGHT_IN   = 0.2
TOP_MARGIN_IN    = 0.5   # room for suptitle
BOTTOM_MARGIN_IN = 0.25
COL_GAP_IN       = 0.35  # horizontal gap between columns
SIDE_MARGIN_IN   = 0.3

MOLL_HEIGHT_IN  = COL_WIDTH_IN * MOLL_ASPECT + TITLE_PAD_IN
PATCH_HEIGHT_IN = COL_WIDTH_IN  # patch is square (NSIDE_PATCH x NSIDE_PATCH)

# %% [markdown]
# ## Helper functions

# %%
def _safe(label):
    return label.replace(" ", "_").replace("/", "_")

def precompute_face_indices(nside):
    npix = hp.nside2npix(nside)
    ipix = np.arange(npix, dtype=np.int32)
    x, y, f = hp.pix2xyf(nside, ipix, nest=True)
    face_idx = {}
    for face_id in range(12):
        mask = f == face_id
        face_idx[face_id] = (ipix[mask].astype(np.int32), x[mask].astype(np.int32), y[mask].astype(np.int32))
    return face_idx

def get_face_2d(map_nest, nside, face_id, face_idx):
    ipix_f, x_f, y_f = face_idx[face_id]
    face_img = np.full((nside, nside), np.nan, dtype=map_nest.dtype)
    face_img[y_f, x_f] = map_nest[ipix_f]
    return face_img

def extract_patch(map_ring, face_id=PATCH_FACE, row=PATCH_ROW, col=PATCH_COL):
    map_nest = hp.reorder(map_ring, r2n=True)
    face_img = get_face_2d(map_nest, NSIDE_MAP, face_id, FACE_IDX)
    return face_img[row*NSIDE_PATCH:(row+1)*NSIDE_PATCH, col*NSIDE_PATCH:(col+1)*NSIDE_PATCH]

def make_patch_mask(nside_map, face_id, row, col, nside_patch, face_idx):
    npix = hp.nside2npix(nside_map)
    mask = np.zeros(npix, dtype=bool)
    ipix_f, x_f, y_f = face_idx[face_id]
    row_mask = (y_f >= row * nside_patch) & (y_f < (row + 1) * nside_patch)
    col_mask = (x_f >= col * nside_patch) & (x_f < (col + 1) * nside_patch)
    patch_mask = row_mask & col_mask
    mask[ipix_f[patch_mask]] = True
    return mask

def with_patch_highlighted(map_ring, patch_mask_nest):
    map_nest = hp.reorder(map_ring, r2n=True).copy()
    map_nest[patch_mask_nest] = np.nan
    return hp.reorder(map_nest, n2r=True)

def add_col_axes(fig, fig_w_in, fig_h_in, col):
    """Create (mollweide, patch, colorbar) axes for one column at exact inch positions."""
    x0_in = SIDE_MARGIN_IN + col * (COL_WIDTH_IN + COL_GAP_IN)

    moll_y1_in = fig_h_in - TOP_MARGIN_IN
    moll_y0_in = moll_y1_in - MOLL_HEIGHT_IN
    patch_y1_in = moll_y0_in - GAP_IN
    patch_y0_in = patch_y1_in - PATCH_HEIGHT_IN
    cbar_y1_in = patch_y0_in - CBAR_PAD_IN
    cbar_y0_in = cbar_y1_in - CBAR_HEIGHT_IN

    def to_frac(x_in, y_in, w_in, h_in):
        return [x_in / fig_w_in, y_in / fig_h_in, w_in / fig_w_in, h_in / fig_h_in]

    moll_ax  = fig.add_axes(to_frac(x0_in, moll_y0_in, COL_WIDTH_IN, MOLL_HEIGHT_IN))
    patch_ax = fig.add_axes(to_frac(x0_in, patch_y0_in, COL_WIDTH_IN, PATCH_HEIGHT_IN))
    cbar_ax  = fig.add_axes(to_frac(x0_in, cbar_y0_in, COL_WIDTH_IN, CBAR_HEIGHT_IN))
    return moll_ax, patch_ax, cbar_ax

def plot_mollweide(moll_ax, data, title, vmax, cmap):
    """Draw into moll_ax, restoring its exact position afterward (mollview repositions
    axes internally on call)."""
    pos = moll_ax.get_position()
    plt.axes(moll_ax)
    hp.mollview(data, hold=True, title=title, min=-vmax, max=vmax, cmap=cmap,
                badcolor="grey", cbar=False)
    moll_ax.set_position(pos)

# %% [markdown]
# ## Precompute face indices & patch mask

# %%
FACE_IDX = precompute_face_indices(NSIDE_MAP)
PATCH_MASK_NEST = make_patch_mask(NSIDE_MAP, PATCH_FACE, PATCH_ROW, PATCH_COL, NSIDE_PATCH, FACE_IDX)

# %% [markdown]
# ## Main plotting loop: data_source -> bin -> eps

# %%
with np.load(SMOOTHED_FILE) as d:
    for data_source, jobs in MOLLWEIDE_JOBS.items():
        for b in BIN_NAMES:
            v_true_smooth = hp.remove_monopole(d[f"true_smooth_{data_source}_bin{b}"])
            true_patch = extract_patch(v_true_smooth)

            for eps in EPS_LIST:
                n_cols = 1 + len(jobs)
                vmax = np.nanpercentile(np.abs(v_true_smooth), 99)

                fig_w_in = 2 * SIDE_MARGIN_IN + n_cols * COL_WIDTH_IN + (n_cols - 1) * COL_GAP_IN
                fig_h_in = (TOP_MARGIN_IN + MOLL_HEIGHT_IN + GAP_IN + PATCH_HEIGHT_IN
                            + CBAR_PAD_IN + CBAR_HEIGHT_IN + BOTTOM_MARGIN_IN)
                fig = plt.figure(figsize=(fig_w_in, fig_h_in))

                # --- column 0: True ---
                moll_ax, patch_ax, cbar_ax = add_col_axes(fig, fig_w_in, fig_h_in, 0)
                plot_mollweide(moll_ax, with_patch_highlighted(v_true_smooth, PATCH_MASK_NEST),
                                "True", vmax, "PRGn_r")

                patch_ax.imshow(true_patch, cmap="PRGn_r", vmin=-vmax, vmax=vmax, interpolation="nearest")
                patch_ax.set_xticks([]); patch_ax.set_yticks([])

                norm = Normalize(vmin=-vmax, vmax=vmax)
                mcolorbar.ColorbarBase(cbar_ax, cmap="PRGn_r", norm=norm,
                                        orientation="horizontal").ax.tick_params(labelsize=8)

                # --- remaining columns: reconstructions ---
                for i, (label, _) in enumerate(jobs):
                    key = f"vhat_smooth_{data_source}_bin{b}_eps{eps}_{_safe(label)}"
                    v_hat_smooth = hp.remove_monopole(d[key])
                    v_hat_patch = extract_patch(v_hat_smooth)

                    recon_cmap = "PRGn" if (data_source == "flamingo" and label in ("QE flamingo", "ViT base/flamingo")) else "PRGn_r"

                    moll_ax, patch_ax, cbar_ax = add_col_axes(fig, fig_w_in, fig_h_in, i + 1)
                    plot_mollweide(moll_ax, with_patch_highlighted(v_hat_smooth, PATCH_MASK_NEST),
                                    TITLE_MAP.get(label, label), vmax, recon_cmap)

                    patch_ax.imshow(v_hat_patch, cmap=recon_cmap, vmin=-vmax, vmax=vmax, interpolation="nearest")
                    patch_ax.set_xticks([]); patch_ax.set_yticks([])

                    norm = Normalize(vmin=-vmax, vmax=vmax)
                    mcolorbar.ColorbarBase(cbar_ax, cmap=recon_cmap, norm=norm,
                                            orientation="horizontal").ax.tick_params(labelsize=8)

                fig.suptitle(f"{data_source} data, bin {b}, eps={eps}", y=1 - (TOP_MARGIN_IN * 0.4 / fig_h_in))
                plt.show()

