# -*- coding: utf-8 -*-
"""Flamingo Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qtmMaXPI1yLe_7FEeVTtxiuuX0XCdgbK
"""

# %% [markdown]
# # Extract raw T/tau shells from FLAMINGO lightcone

# %%
import os
import zipfile
import hdfstream
import lightcone_io as lc
import numpy as np
import healpy as hp
import matplotlib.pyplot as plt
import gc

DATA_DIR = "/mnt/beegfs/scoulombe"
SHELL_NRS = list(range(8, 20))
OUT_PATH = os.path.join(DATA_DIR, "flamingo_T_tau_shells8-19.npz")

# %% [markdown]
# ## Pull each shell's T (DopplerB) and tau (DM) maps from the remote
# lightcone and stream them straight into an npz/zip archive (skipped if
# the output file already exists).

# %%
if os.path.exists(OUT_PATH):
    print(f"Found existing {OUT_PATH}, skipping shell extraction.")
else:
    T_dir = "FLAMINGO/L1_m9/L1_m9/healpix_maps/nside_4096"
    T_name = "lightcone0"

    root = hdfstream.open("cosma", "/")
    shell_array = lc.ShellArray(T_dir, T_name, remote_dir=root)

    # Write directly into the npz's underlying zip archive, one array at a
    # time, instead of accumulating all 24 arrays in a dict before saving.
    with zipfile.ZipFile(OUT_PATH, mode="w") as zf:
        with zf.open("shell_nrs.npy", "w") as fp:
            np.lib.format.write_array(fp, np.array(SHELL_NRS))

        for shell_nr in SHELL_NRS:
            print(f"Processing shell {shell_nr} ...")
            shell = shell_array[shell_nr]

            T_data = np.asarray(shell["DopplerB"][...])
            with zf.open(f"T_shell{shell_nr}.npy", "w") as fp:
                np.lib.format.write_array(fp, T_data)
            del T_data
            gc.collect()

            tau_data = np.asarray(shell["DM"][...])
            with zf.open(f"tau_shell{shell_nr}.npy", "w") as fp:
                np.lib.format.write_array(fp, tau_data)
            del tau_data
            gc.collect()

    print(f"Saved all {len(SHELL_NRS)} shells -> {OUT_PATH}")

# %% [markdown]
# ## Load the extracted shells back in

# %%
f = np.load(OUT_PATH)
shell_nrs = f["shell_nrs"]

# %% [markdown]
# # Binned T/tau maps
# ## Re-import + config (this was its own notebook section originally)

# %%
import os
import numpy as np
import healpy as hp

DATA_DIR = "/mnt/beegfs/scoulombe"

BINNED_OUT_PATH = os.path.join(DATA_DIR, "flamingo_T_tau_binned.npz")

# %% [markdown]
# ## Sum shells into 3 T/tau bins (skipped if BINNED_OUT_PATH already exists)
#
# Each bin sums T and (mean-subtracted, unit-converted) tau across its 4
# shells. tau is rescaled from comoving-length units into an optical-depth
# scale via the two constant factors below.

# %%
BINNED_OUT_PATH = os.path.join(DATA_DIR, "flamingo_T_tau_binned.npz")

if os.path.exists(BINNED_OUT_PATH):
    print(f"Found existing {BINNED_OUT_PATH}, skipping binning.")
else:
    IN_PATH = os.path.join(DATA_DIR, "flamingo_T_tau_shells8-19.npz")
    f_shells = np.load(IN_PATH)

    BIN_SHELL_RANGES = [
        (8, 9, 10, 11),
        (12, 13, 14, 15),
        (16, 17, 18, 19),
    ]

    data = {}
    for bin_idx, shells_in_bin in enumerate(BIN_SHELL_RANGES):
        print(f"Bin {bin_idx}: shells {shells_in_bin}")

        T_sum = None
        tau_sum = None

        for shell_nr in shells_in_bin:
            T_field = f_shells[f"T_shell{shell_nr}"]
            tau_field = f_shells[f"tau_shell{shell_nr}"].copy()

            tau_mean = np.mean(tau_field)
            tau_field -= tau_mean
            tau_field *= (3.085677581e22)**(-2)
            tau_field *= 6.65e-29

            if T_sum is None:
                T_sum = T_field.astype(np.float64).copy()
                tau_sum = tau_field.astype(np.float64).copy()
            else:
                T_sum += T_field
                tau_sum += tau_field

            del T_field, tau_field
            gc.collect()

        data[f"T_bin{bin_idx}"] = T_sum
        data[f"tau_bin{bin_idx}"] = tau_sum
        data[f"bin{bin_idx}_shells"] = np.array(shells_in_bin)
        del T_sum, tau_sum
        gc.collect()

    data["bin_nrs"] = np.array([0, 1, 2])
    np.savez(BINNED_OUT_PATH, **data)
    print(f"Saved binned maps -> {BINNED_OUT_PATH}")

    del data, f_shells
    gc.collect()

# %% [markdown]
# ## Load the binned maps back in

# %%
f_binned = np.load(BINNED_OUT_PATH)
bin_nrs = f_binned["bin_nrs"]

# %% [markdown]
# ## v = T / tau per bin, flooring tau near zero to avoid blow-ups

# %%
v_maps = {}
frac_floored_dict = {}

for bin_idx in bin_nrs:
    T_field = f_binned[f"T_bin{bin_idx}"]
    tau_field = f_binned[f"tau_bin{bin_idx}"]
    tau_std = np.std(tau_field)
    floor = 0.05 * tau_std
    floored = np.abs(tau_field) < floor
    sign = np.where(tau_field >= 0, 1.0, -1.0)
    tau_floored = np.where(floored, sign * floor, tau_field)
    v_map = T_field / tau_floored
    n_floored = np.sum(floored)
    frac_floored = n_floored / v_map.size
    del floored, sign, tau_floored, T_field, tau_field
    gc.collect()
    print(f"Bin {bin_idx} - Floor Fraction:", frac_floored)
    v_maps[bin_idx] = v_map
    frac_floored_dict[bin_idx] = frac_floored

# %% [markdown]
# ## Normalize v and tau using bin-0 std
# (downgrade to nside_out first, then compute std, so nside=2048 fields end
# up ~unit variance)

# %%
# ##=====================================
# ##  NORMALIZE v AND tau USING BIN 0 STD
# ##  (udgrade first, then compute std, so nside=2048 fields ~unit variance)
# ##=====================================
nside_out = 2048

tau_maps_lores = {}
v_maps_lores = {}
for bin_idx in bin_nrs:
    tau_field = f_binned[f"tau_bin{bin_idx}"]
    tau_maps_lores[bin_idx] = hp.ud_grade(tau_field, nside_out)
    del tau_field

    v_field = v_maps.pop(bin_idx)
    v_maps_lores[bin_idx] = hp.ud_grade(v_field, nside_out)
    del v_field

    gc.collect()

del v_maps
f_binned.close()
del f_binned
gc.collect()

# %% [markdown]
# ## Compute normalization factors from bin 0 (post-downgrade) and apply

# %%
# compute normalization factors from bin 0, AFTER downgrading
tau_std0 = np.std(tau_maps_lores[0])
v_std0 = np.std(v_maps_lores[0])
print("Normalization factors from bin 0 (post-udgrade):")
print("  tau_std0:", tau_std0)
print("  v_std0:  ", v_std0)

tau_maps_norm = {}
v_maps_norm = {}
for bin_idx in bin_nrs:
    tau_maps_norm[bin_idx] = tau_maps_lores[bin_idx] / tau_std0
    v_maps_norm[bin_idx] = v_maps_lores[bin_idx] / v_std0
    print(f"Bin {bin_idx} - normalized tau std: {np.std(tau_maps_norm[bin_idx]):.4g}, "
          f"normalized v std: {np.std(v_maps_norm[bin_idx]):.4g}")

del tau_maps_lores, v_maps_lores
gc.collect()

# %% [markdown]
# ## Stack into the 6-field list [tau0, tau1, tau2, v0, v1, v2] and compute alms

# %%
field_names = ["tau0", "tau1", "tau2", "v0", "v1", "v2"]
fields = []
for i, name in enumerate(field_names):
    if i < 3:
        raw = tau_maps_norm.pop(i)
    else:
        raw = v_maps_norm.pop(i - 3)
    fields.append(raw)
nside = hp.get_nside(fields[0])
lmax = 3 * nside - 1
print(f"nside={nside}, lmax={lmax}, n_fields={len(fields)}")
del tau_maps_norm, v_maps_norm
gc.collect()

ALMS_PATH = os.path.join(DATA_DIR, f"alms_nside{nside}_lmax{lmax}_norm.npz")

if os.path.exists(ALMS_PATH):
    print(f"Found existing {ALMS_PATH}, loading alms.")
    alms_data = np.load(ALMS_PATH)
    alms = [alms_data[name] for name in field_names]
else:
    print("Computing alms...")
    alms = [hp.map2alm(m, lmax=lmax) for m in fields]
    np.savez(ALMS_PATH, **dict(zip(field_names, alms)))
    print(f"Saved alms -> {ALMS_PATH}")

# %% [markdown]
# ## Compute (or load cached) full auto/cross power spectra across all 6 fields

# %%
CLS_PATH = os.path.join(DATA_DIR, f"cls_all_nside{nside}_lmax{lmax}_norm.npz")

n = len(field_names)
labels = [f"{field_names[i]}-{field_names[i]}" for i in range(n)]
for offset in range(1, n):
    for i in range(n - offset):
        j = i + offset
        labels.append(f"{field_names[i]}-{field_names[j]}")
if os.path.exists(CLS_PATH):
    print(f"Found existing {CLS_PATH}, loading cls.")
    cls_data = np.load(CLS_PATH)
    cls_all = [cls_data[str(k)] for k in range(len(labels))]
else:
    print("Computing cls...")
    cls_all = hp.alm2cl(alms, lmax=lmax)
    np.savez(CLS_PATH, **{str(k): c for k, c in enumerate(cls_all)})
    print(f"Saved cls -> {CLS_PATH}")
del alms
gc.collect()
print(len(cls_all), len(labels))
for lbl in labels:
    print(lbl)

# %% [markdown]
# ## Smoothing helper (used below for the synthetic-realization spectra)

# %%
def moving_average(y, window):
    """Simple centered moving average via convolution, edge-padded so the
    output is the same length as the input (no shrinkage at the boundaries)."""
    if window <= 1:
        return y
    kernel = np.ones(window) / window
    pad = window // 2
    y_padded = np.pad(y, pad, mode="edge")
    smoothed = np.convolve(y_padded, kernel, mode="same")
    return smoothed[pad:pad + len(y)]

WINDOW = 5

# %% [markdown]
# ## Generate (or load cached) a synthetic realization from the smoothed
# spectra, and recover its spectra to check against the input

# %%
# Build the smoothed cls list once (window=5, matching the plotting cells)
cls_all_smoothed = [moving_average(c, WINDOW) for c in cls_all]

SYNTH_PATH = os.path.join(DATA_DIR, f"synth_fields_nside{nside}_lmax{lmax}_smoothed.npz")

if os.path.exists(SYNTH_PATH):
    print(f"Found existing {SYNTH_PATH}, loading synthetic realization.")
    synth_data = np.load(SYNTH_PATH)
    synth_fields = [synth_data[name] for name in field_names]
else:
    print("Generating new random realization...")
    synth_fields = hp.synfast(cls_all_smoothed, nside=nside, lmax=lmax, pol=False, new=True)
    np.savez(SYNTH_PATH, **dict(zip(field_names, synth_fields)))
    print(f"Saved realization -> {SYNTH_PATH}")

CLS_SYNTH_PATH = os.path.join(DATA_DIR, f"cls_synth_nside{nside}_lmax{lmax}_smoothed.npz")
if os.path.exists(CLS_SYNTH_PATH):
    print(f"Found existing {CLS_SYNTH_PATH}, loading recovered cls.")
    cls_synth_data = np.load(CLS_SYNTH_PATH)
    cls_synth = [cls_synth_data[str(k)] for k in range(len(labels))]
else:
    print("Computing alms/cls from synthetic fields...")
    alms_synth = [hp.map2alm(m, lmax=lmax) for m in synth_fields]
    cls_synth = hp.alm2cl(alms_synth, lmax=lmax)
    np.savez(CLS_SYNTH_PATH, **{str(k): c for k, c in enumerate(cls_synth)})
    print(f"Saved recovered cls -> {CLS_SYNTH_PATH}")
    del alms_synth
    gc.collect()

# %% [markdown]
# # CAMB data
# Generate a reference CMB temperature power spectrum via CAMB.

# %%
# ##=====================================
# ##  CAMB DATA
# ##=====================================
import camb

pars = camb.set_params(
    H0=67.5, ombh2=0.022, omch2=0.122, mnu=0.06, omk=0,
    tau=0.06, As=2e-9, ns=0.965, halofit_version='mead', lmax=lmax,
)
results = camb.get_results(pars)
powers = results.get_cmb_power_spectra(pars, CMB_unit=None, raw_cl=True)
totCL = powers['total']
cmb = totCL[:, 0]

print(cmb.shape)

# %% [markdown]
# ## Normalize the CMB Cl by the v/tau variance product, synthesize the
# matching instrument-noise map, and save normalization factors to disk

# %%
# ##=====================================
# ##  NORMALIZE CMB Cl BY v/tau VARIANCE PRODUCT
# ##=====================================

def make_noise_cl(cmb_cl, tau_std0, v_std0, lmax):
    """Normalize the CMB Cl by the product of the (bin-0) v and tau
    variances, matching the scale of the normalized v/tau fields.
    Truncates/pads cmb_cl to length lmax+1 to match the current pipeline's
    ell range, and zeros the monopole."""
    noise_cl = np.array(cmb_cl[:lmax + 1], dtype=np.float64).copy()
    if len(noise_cl) < lmax + 1:
        noise_cl = np.pad(noise_cl, (0, lmax + 1 - len(noise_cl)))
    noise_cl[0] = 0.0

    variance = (tau_std0 ** 2) * (v_std0 ** 2)
    noise_cl = noise_cl / variance
    return noise_cl

noise_cl = make_noise_cl(cmb, tau_std0, v_std0, lmax)

def make_noise(noise_cl, nside, lmax):
    return hp.synfast(noise_cl, nside, lmax=lmax)

noise_ring = make_noise(noise_cl, nside, lmax).astype(np.float32)

NORM_PATH = os.path.join(DATA_DIR, f"norm_factors_nside{nside}.npz")
np.savez(NORM_PATH, tau_std0=tau_std0, v_std0=v_std0)
print(f"Saved normalization factors -> {NORM_PATH}")