# -*- coding: utf-8 -*-
"""Training Vision Transformer Model on Gaussian Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14XoyUhAbl_ajSVsfevzmmgoegtwg5M77
"""

"""
Binned multi-shell ViT training pipeline.

Reconstructs v0, v1, v2 (3 output channels) from Tnoise = T + eps*noise plus
tau0, tau1, tau2 (4 input channels), where T = sum_i(v_i * tau_i) is the
already-generated integrated signal across all 3 bins.

Structural decisions this script implements (see conversation for full
reasoning behind each):
  1. 4 input channels [Tnoise, tau0, tau1, tau2], 3 output channels [v0,v1,v2]
  2. One extra test realization (seed=32), generated the same way as the
     32 train/val realizations, saved separately and never used in training
  3. Loss weights: pooled across v0-2 (already computed, binned_loss_scale.npz)
  4. v, tau, noise, T cached once (eps-agnostic); Tnoise composed on the fly
  5. One Mollweide + one patch-comparison plot set per bin (3 sets) per snapshot
  6. SNAPSHOT_TAG = "binned" (no single shell_nr anymore)
  7. Loss averaged across the 3 output channels (not summed)
  8. Same EPS_LIST / curriculum staging logic as before, built parametrically
  9. NSIDE_PATCH = 256 (matches binned_loss_scale.npz)
  10. 90/10 train/val split, kept as an adjustable parameter
  11. Patch cache: 4 stacked files (tau_stack, v_target_stack, noise, T),
      same resumable/chunked build approach, sequential (not parallelized)
  12. Training starts from scratch; resumable if interrupted
  13. Same hyperparameters as before, kept as easily-editable constants
  14. Same model architecture (embed_dim=64, depth=4, n_heads=4, mlp_ratio=4)
  15. n_spec_bins / spec_loss_eps loaded from binned_loss_scale.npz
  16. Patch-cache build is sequential (not parallelized)

  NEW CHANGES:
  1. slower curriculum with more intermediate stages and a 2 tier epsilon retirement process
  2. patience raised and min delta lowered

  NEW CHANGES - bigger model (embed 64-128, depth 4-5)
"""

import os
import numpy as np
import healpy as hp
import camb

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

import gc
import glob
import re

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

##=====================================
##  DATALOADER WORKER COUNT
##=====================================
# Empirically finds the largest num_workers value DataLoader can actually
# use on this machine (some cluster configs fail above a certain worker
# count), by trying it on a throwaway dataset and backing off on failure.
def _probe_num_workers(max_cap=8):
    slurm_cpus = os.environ.get("SLURM_CPUS_PER_TASK")
    detected = int(slurm_cpus) if slurm_cpus else (os.cpu_count() or 1)
    candidate = max(0, min(detected, max_cap))

    class _DummyDS(Dataset):
        def __len__(self):
            return 32
        def __getitem__(self, idx):
            return torch.zeros(1)

    while candidate > 0:
        try:
            _loader = DataLoader(_DummyDS(), batch_size=8, num_workers=candidate)
            for _ in _loader:
                pass
            del _loader
            print(f"[perf] NUM_WORKERS probe succeeded with {candidate} workers (detected {detected} CPUs, cap {max_cap})")
            return candidate
        except Exception as e:
            print(f"[perf] NUM_WORKERS probe failed at {candidate} workers ({e}); trying fewer")
            candidate -= 1

    print("[perf] NUM_WORKERS probe: falling back to 0 (single-process loading)")
    return 0

NUM_WORKERS = _probe_num_workers(max_cap=10)
PREFETCH_FACTOR = 4 if NUM_WORKERS > 0 else None
print(f"[perf] Using NUM_WORKERS={NUM_WORKERS}, PREFETCH_FACTOR={PREFETCH_FACTOR}")

##=====================================
##  PARAMETERS  (hyperparameters kept as plain constants -- edit here)
##=====================================
RUN_SEED = 0
torch.manual_seed(RUN_SEED)

N_REALIZATIONS = int(os.environ.get("N_REALIZATIONS", 64))
TEST_SEED      = N_REALIZATIONS  # always the seed immediately past the last training seed
NSIDE_MAP      = 2048
NSIDE_PATCH    = 256
LMAX           = 3 * NSIDE_MAP - 1
SMOOTH_WINDOW  = 5   # must match the FLAMINGO notebook / generate_realizations.py

BIN_NAMES = ["0", "1", "2"]  # v/tau bin suffixes
n_bins = len(BIN_NAMES)

n_patches_per_map = 12 * (NSIDE_MAP // NSIDE_PATCH) ** 2

DATA_DIR = "/mnt/beegfs/scoulombe"
os.makedirs(DATA_DIR, exist_ok=True)

# SNAPSHOT_TAG controls checkpoint/history/resume-state/plot filenames only.
# Override via the SNAPSHOT_TAG environment variable (e.g. for a throwaway
# test run) without affecting the patch cache or test realization files,
# which are always shared/reused regardless of this value -- see
# PATCH_CACHE_TAG below.
SNAPSHOT_TAG = os.environ.get("SNAPSHOT_TAG", "binned_finegrained_v2_bigmodel_n64_v1")
print(f"Using SNAPSHOT_TAG='{SNAPSHOT_TAG}' for checkpoint/history/resume/plot files")

# PATCH_CACHE_TAG is intentionally fixed (not overridable) so a test run and
# the real run always reuse the same expensive-to-build patch cache and test
# realization, regardless of what SNAPSHOT_TAG is set to.
PATCH_CACHE_TAG = "binned"

# --- adjustable train/val split fraction ---
VAL_FRACTION_OF_REALIZATIONS = 0.1  # fraction of the 32 realizations held for validation

# --- realization files (already generated) ---
REAL_FILES = {
    f"v{b}": os.path.join(DATA_DIR, f"realizations_v{b}_nside{NSIDE_MAP}_n{N_REALIZATIONS}_norm_smooth{SMOOTH_WINDOW}.npy")
    for b in BIN_NAMES
}
REAL_FILES.update({
    f"tau{b}": os.path.join(DATA_DIR, f"realizations_tau{b}_nside{NSIDE_MAP}_n{N_REALIZATIONS}_norm_smooth{SMOOTH_WINDOW}.npy")
    for b in BIN_NAMES
})
REAL_FILES["T"] = os.path.join(DATA_DIR, f"realizations_T_nside{NSIDE_MAP}_n{N_REALIZATIONS}.npy")
REAL_FILES["cmbnoise"] = os.path.join(DATA_DIR, f"realizations_cmbnoise_nside{NSIDE_MAP}_n{N_REALIZATIONS}.npy")

# --- held-out test realization files (generated by this script if missing) ---
TEST_FILES = {
    name: os.path.join(DATA_DIR, f"test_realization_{name}_nside{NSIDE_MAP}_binned_seed{TEST_SEED}.npy")
    for name in ["v0", "v1", "v2", "tau0", "tau1", "tau2", "T", "cmbnoise"]
}

CLS_PATH  = os.path.join(DATA_DIR, f"cls_all_nside{NSIDE_MAP}_lmax{LMAX}_norm.npz")
NORM_PATH = os.path.join(DATA_DIR, f"norm_factors_nside{NSIDE_MAP}.npz")
LOSS_SCALE_FILE = os.path.join(DATA_DIR, "binned_loss_scale.npz")

# --- EPS curriculum: finer intermediate steps added between 0 and 0.1 for a
# more gradual ramp. TIER1_RETIRE = the new intermediates (retire first).
# TIER2_RETIRE = the original odd values (only start retiring once every
# active TIER1 member is already floored) -- see build_curriculum_stages.
EPS_LIST = [0.0, 0.00625, 0.0125, 0.01875, 0.025, 0.03125, 0.0375, 0.04375,
            0.05, 0.05625, 0.0625, 0.06875, 0.075, 0.08125, 0.0875, 0.09375,
            0.1, 0.15, 0.2, 0.3, 0.4, 0.6, 0.8, 1.0, 1.25, 1.5]
EPS_MAX = max(EPS_LIST)

TIER1_RETIRE = {0.00625, 0.01875, 0.03125, 0.04375, 0.05625, 0.06875, 0.08125, 0.09375}
TIER2_RETIRE = {0.0125, 0.0375, 0.0625, 0.0875}

N_VAL_REALIZATIONS = max(1, int(VAL_FRACTION_OF_REALIZATIONS * N_REALIZATIONS))
VAL_REALIZATIONS   = list(range(N_REALIZATIONS - N_VAL_REALIZATIONS, N_REALIZATIONS))
TRAIN_REALIZATIONS = list(range(0, N_REALIZATIONS - N_VAL_REALIZATIONS))
print(f"Train realizations: {TRAIN_REALIZATIONS}")
print(f"Val realizations:   {VAL_REALIZATIONS}")

##=====================================
##  moving_average  (must match FLAMINGO notebook / generate_realizations.py)
##=====================================
# Simple edge-padded box-car smoother, applied to power spectra before
# synfast so the synthetic test realization matches the smoothing already
# baked into the training realizations.
def moving_average(y, window):
    if window <= 1:
        return y
    kernel = np.ones(window) / window
    pad = window // 2
    y_padded = np.pad(y, pad, mode="edge")
    smoothed = np.convolve(y_padded, kernel, mode="same")
    return smoothed[pad:pad + len(y)]

##=====================================
##  PATCH / HEALPIX GEOMETRY FUNCTIONS  (unchanged from original pipeline)
##=====================================
def precompute_face_indices(nside):
    # For each of the 12 HEALPix base faces, cache the pixel indices and their
    # (x, y) position within that face (NEST ordering), so later reshaping
    # a NEST map into 12 square face images doesn't need to recompute this.
    npix = hp.nside2npix(nside)
    ipix = np.arange(npix, dtype=np.int32)
    x, y, f = hp.pix2xyf(nside, ipix, nest=True)
    face_idx = {}
    for face_id in range(12):
        mask = f == face_id
        face_idx[face_id] = (ipix[mask].astype(np.int32), x[mask].astype(np.int32), y[mask].astype(np.int32))
    return face_idx

FACE_IDX = precompute_face_indices(NSIDE_MAP)

def get_face_2d(map_nest, nside, face_id, face_idx=None):
    # Reshape one HEALPix face (NEST-ordered map) into a 2D (nside x nside)
    # image. If face_idx wasn't precomputed, fall back to computing it inline.
    if face_idx is not None:
        ipix_f, x_f, y_f = face_idx[face_id]
        face_img = np.full((nside, nside), np.nan, dtype=map_nest.dtype)
        face_img[y_f, x_f] = map_nest[ipix_f]
        assert not np.isnan(face_img).any(), f"Face {face_id} has unfilled pixels — reshape failed"
        return face_img
    npix = hp.nside2npix(nside)
    ipix = np.arange(npix)
    x, y, f = hp.pix2xyf(nside, ipix, nest=True)
    mask = f == face_id
    face_img = np.full((nside, nside), np.nan)
    face_img[y[mask], x[mask]] = map_nest[ipix[mask]]
    assert not np.isnan(face_img).any(), f"Face {face_id} has unfilled pixels — reshape failed"
    return face_img

def extract_all_patches_from_map(map_nest, nside_map, nside_patch, face_idx=FACE_IDX):
    # Slice every face of a NEST map into non-overlapping nside_patch x nside_patch
    # tiles and stack them into one (n_patches, nside_patch, nside_patch) array.
    n_per_side = nside_map // nside_patch
    n_patches = 12 * n_per_side * n_per_side
    out = np.empty((n_patches, nside_patch, nside_patch), dtype=map_nest.dtype)
    idx = 0
    for face_id in range(12):
        face_img = get_face_2d(map_nest, nside_map, face_id, face_idx)
        for pr in range(n_per_side):
            for pc in range(n_per_side):
                out[idx] = face_img[pr*nside_patch:(pr+1)*nside_patch,
                                     pc*nside_patch:(pc+1)*nside_patch]
                idx += 1
    return out

_PATCH_PIXEL_IDX_CACHE = {}

def precompute_patch_pixel_indices(nside_map, nside_patch, face_idx=FACE_IDX):
    # For each patch tile, cache which full-sky HEALPix pixel index each of its
    # (nside_patch x nside_patch) cells maps back to -- the inverse of
    # extract_all_patches_from_map, needed to reassemble predictions later.
    n_per_side = nside_map // nside_patch
    n_patches = 12 * n_per_side * n_per_side
    idx_out = np.empty((n_patches, nside_patch, nside_patch), dtype=np.int64)
    patch_i = 0
    for face_id in range(12):
        ipix_f, x_f, y_f = face_idx[face_id]
        face_grid = np.full((nside_map, nside_map), -1, dtype=np.int64)
        face_grid[y_f, x_f] = ipix_f
        assert not (face_grid == -1).any(), f"Face {face_id} has unfilled pixels — index precompute failed"
        for pr in range(n_per_side):
            for pc in range(n_per_side):
                idx_out[patch_i] = face_grid[pr*nside_patch:(pr+1)*nside_patch,
                                              pc*nside_patch:(pc+1)*nside_patch]
                patch_i += 1
    return idx_out

def reassemble_from_stack(patch_stack, nside_map, nside_patch):
    """Single-channel reassembly: patch_stack shape (N_patches, H, W)."""
    key = (nside_map, nside_patch)
    if key not in _PATCH_PIXEL_IDX_CACHE:
        _PATCH_PIXEL_IDX_CACHE[key] = precompute_patch_pixel_indices(nside_map, nside_patch)
    pix_idx = _PATCH_PIXEL_IDX_CACHE[key]
    assert patch_stack.shape == pix_idx.shape, (
        f"patch_stack shape {patch_stack.shape} does not match expected {pix_idx.shape}"
    )
    out = np.full(hp.nside2npix(nside_map), np.nan, dtype=patch_stack.dtype)
    out[pix_idx.ravel()] = patch_stack.ravel()
    assert not np.isnan(out).any(), "Some pixels were not filled during reassembly!"
    return out

def reassemble_channels_from_stack(patch_stack_multi, nside_map, nside_patch):
    """Multi-channel reassembly: patch_stack_multi shape (N_patches, C, H, W).
    Returns a list of C full-sky maps (NEST order)."""
    n_channels = patch_stack_multi.shape[1]
    return [reassemble_from_stack(patch_stack_multi[:, c], nside_map, nside_patch)
            for c in range(n_channels)]

def reconstruct_full_maps_multi(model, Tnoise_map_nest, tau_maps_nest, nside_map, nside_patch, eps, batch_size=256): ##CHANGE THIS BACK TO 256
    """
    Runs the model over every patch of the full map and reassembles the
    predictions into n_bins full-sky maps.
    tau_maps_nest: list of n_bins NEST maps [tau0, tau1, tau2].
    Returns: list of n_bins reconstructed NEST maps [v0_pred, v1_pred, v2_pred].
    """
    # Patchify inputs, run the model in batches (batched for memory, not for
    # speed -- see the ##CHANGE THIS BACK TO 256 note above), then reassemble
    # the per-channel predictions back into full-sky maps.
    Tnoise_stack = extract_all_patches_from_map(Tnoise_map_nest, nside_map, nside_patch)
    tau_stacks = [extract_all_patches_from_map(t, nside_map, nside_patch) for t in tau_maps_nest]

    n_patches = Tnoise_stack.shape[0]
    preds = np.empty((n_patches, n_bins, nside_patch, nside_patch), dtype=np.float32)

    with torch.no_grad():
        for start in range(0, n_patches, batch_size):
            end = min(start + batch_size, n_patches)
            inp = np.stack([Tnoise_stack[start:end]] + [ts[start:end] for ts in tau_stacks], axis=1)
            inp_t = torch.tensor(inp, dtype=torch.float32).to(device)
            eps_t = torch.full((inp_t.shape[0],), eps, dtype=torch.float32, device=device)
            pred = model(inp_t, eps_t).cpu().numpy()
            preds[start:end] = pred

    return reassemble_channels_from_stack(preds, nside_map, nside_patch)

print("Patch/geometry functions ready")

##=====================================
##  GENERATE HELD-OUT TEST REALIZATION  (seed=32, same method as training set)
##=====================================
def generate_test_realization():
    if all(os.path.exists(p) for p in TEST_FILES.values()):
        print("Test realization files already exist, skipping generation.")
        return

    print("Generating held-out test realization (seed={})...".format(TEST_SEED))

    # Synthesize v0-2/tau0-2 from the same (smoothed) power spectra used for
    # the training realizations, at a seed (TEST_SEED) that's guaranteed to
    # be past every training seed (0..N_REALIZATIONS-1).
    cls_data = np.load(CLS_PATH)
    field_names = ["tau0", "tau1", "tau2", "v0", "v1", "v2"]
    n_spectra = len(field_names) * (len(field_names) + 1) // 2
    cls_all = [cls_data[str(k)] for k in range(n_spectra)]
    cls_all_smoothed = [moving_average(c, SMOOTH_WINDOW) for c in cls_all]

    np.random.seed(TEST_SEED)
    synth = hp.synfast(cls_all_smoothed, NSIDE_MAP, lmax=LMAX, pol=False, new=True)
    synth = dict(zip(field_names, synth))

    norm_data = np.load(NORM_PATH)
    tau_std0 = float(norm_data["tau_std0"])
    v_std0 = float(norm_data["v_std0"])

    # Build a CMB temperature power spectrum via CAMB, and use it (rescaled
    # by the same tau/v normalization used for the signal channels) as the
    # power spectrum for the synthetic instrument-noise realization.
    pars = camb.set_params(
        H0=67.5, ombh2=0.022, omch2=0.122, mnu=0.06, omk=0,
        tau=0.06, As=2e-9, ns=0.965, halofit_version='mead', lmax=LMAX,
    )
    results = camb.get_results(pars)
    powers = results.get_cmb_power_spectra(pars, CMB_unit=None, raw_cl=True)
    totCL = powers['total']
    cmb = totCL[:, 0]
    noise_cl = np.array(cmb[:LMAX + 1], dtype=np.float64).copy()
    if len(noise_cl) < LMAX + 1:
        noise_cl = np.pad(noise_cl, (0, LMAX + 1 - len(noise_cl)))
    noise_cl[0] = 0.0
    noise_cl = noise_cl / ((tau_std0 ** 2) * (v_std0 ** 2))

    np.random.seed(TEST_SEED)
    noise_test = hp.synfast(noise_cl, NSIDE_MAP, lmax=LMAX).astype(np.float32)

    # T = sum_i(v_i * tau_i), the same integrated-signal construction used
    # for the training realizations.
    T_test = np.zeros(hp.nside2npix(NSIDE_MAP), dtype=np.float64)
    for b in BIN_NAMES:
        T_test += synth[f"v{b}"].astype(np.float64) * synth[f"tau{b}"].astype(np.float64)
    T_test = T_test.astype(np.float32)

    for b in BIN_NAMES:
        np.save(TEST_FILES[f"v{b}"], synth[f"v{b}"].astype(np.float32))
        np.save(TEST_FILES[f"tau{b}"], synth[f"tau{b}"].astype(np.float32))
    np.save(TEST_FILES["T"], T_test)
    np.save(TEST_FILES["cmbnoise"], noise_test)

    del synth, T_test, noise_test
    gc.collect()
    print("Saved test realization files:", *TEST_FILES.values(), sep="\n  ")

generate_test_realization()

##=====================================
##  PATCH CACHE (RESUMABLE, SEQUENTIAL, 4 STACKED FILES)
##=====================================
def patch_cache_filename_base_for(n_realizations):
    return os.path.join(DATA_DIR, f"patch_cache_nmap{NSIDE_MAP}_npatch{NSIDE_PATCH}_nreal{n_realizations}_{PATCH_CACHE_TAG}")

def patch_cache_filename_base():
    return patch_cache_filename_base_for(N_REALIZATIONS)

def _cache_files_complete(n_realizations):
    base = patch_cache_filename_base_for(n_realizations)
    suffixes = ["_tau_stack.npy", "_v_target_stack.npy", "_noise.npy", "_T.npy"]
    return all(os.path.exists(base + s) for s in suffixes)

def find_source_cache_n(target_n):
    """
    Look for the largest existing, COMPLETE patch cache with n_realizations
    target_n, so a cache build for a larger N_REALIZATIONS can copy that
    prefix forward instead of reprocessing every realization from scratch.
    Realizations are always laid out in index order (0..N-1) as contiguous
    patch blocks, so any smaller cache is always an exact prefix of a larger
    one -- this is what makes copy-forward valid no matter how many times
    N_REALIZATIONS grows in the future, with no manual bookkeeping needed.
    """
    # Scan for cache files under this tag with any n_realizations count, and
    # keep only those (a) smaller than target_n and (b) actually complete.
    pattern = os.path.join(
        DATA_DIR, f"patch_cache_nmap{NSIDE_MAP}_npatch{NSIDE_PATCH}_nreal*_{PATCH_CACHE_TAG}_tau_stack.npy"
    )
    found = []
    for path in glob.glob(pattern):
        m = re.search(rf"_nreal(\d+)_{re.escape(PATCH_CACHE_TAG)}_tau_stack\.npy$", path)
        if not m:
            continue
        n_candidate = int(m.group(1))
        if n_candidate < target_n and _cache_files_complete(n_candidate):
            found.append(n_candidate)
    return max(found) if found else None

def _copy_memmap_prefix(src_path, dst_memmap, n_rows, chunk_size=2000):
    """Copy the first n_rows rows from src_path into dst_memmap, chunked so
    we never hold the full array in RAM at once."""
    src = np.load(src_path, mmap_mode="r")
    for start in range(0, n_rows, chunk_size):
        end = min(start + chunk_size, n_rows)
        dst_memmap[start:end] = np.array(src[start:end])
    del src

def build_and_save_stage_chunked_binned():
    # Build the patch cache for all N_REALIZATIONS realizations, writing to
    # memory-mapped .npy files so this can be interrupted and resumed:
    #   - if a smaller complete cache exists, its patches are copied forward
    #     first (find_source_cache_n / _copy_memmap_prefix);
    #   - remaining realizations are processed one at a time, flushing to
    #     disk and recording progress after each;
    #   - on completion the "_tmp_*" files are renamed to their final names.
    filename_base = patch_cache_filename_base()
    final_tau_file   = filename_base + "_tau_stack.npy"
    final_v_file     = filename_base + "_v_target_stack.npy"
    final_noise_file = filename_base + "_noise.npy"
    final_T_file     = filename_base + "_T.npy"

    if all(os.path.exists(f) for f in [final_tau_file, final_v_file, final_noise_file, final_T_file]):
        print(f"{filename_base} already exists, skipping generation")
        return filename_base

    v_mmaps   = {b: np.load(REAL_FILES[f"v{b}"], mmap_mode="r") for b in BIN_NAMES}
    tau_mmaps = {b: np.load(REAL_FILES[f"tau{b}"], mmap_mode="r") for b in BIN_NAMES}
    noise_mmap = np.load(REAL_FILES["cmbnoise"], mmap_mode="r")
    T_mmap = np.load(REAL_FILES["T"], mmap_mode="r")

    total_patches = N_REALIZATIONS * n_patches_per_map

    tmp_tau_file   = filename_base + "_tmp_tau_stack.npy"
    tmp_v_file     = filename_base + "_tmp_v_target_stack.npy"
    tmp_noise_file = filename_base + "_tmp_noise.npy"
    tmp_T_file     = filename_base + "_tmp_T.npy"
    progress_file  = filename_base + "_progress.txt"

    if os.path.exists(progress_file) and os.path.exists(tmp_tau_file):
        with open(progress_file) as f:
            start_i = int(f.read().strip())
        print(f"Resuming in-progress build for n={N_REALIZATIONS} from realization {start_i}")
        tau_out   = np.lib.format.open_memmap(tmp_tau_file, mode="r+")
        v_out     = np.lib.format.open_memmap(tmp_v_file, mode="r+")
        noise_out = np.lib.format.open_memmap(tmp_noise_file, mode="r+")
        T_out     = np.lib.format.open_memmap(tmp_T_file, mode="r+")
    else:
        tau_out   = np.lib.format.open_memmap(tmp_tau_file, mode="w+", dtype=np.float32,
                                               shape=(total_patches, n_bins, NSIDE_PATCH, NSIDE_PATCH))
        v_out     = np.lib.format.open_memmap(tmp_v_file, mode="w+", dtype=np.float32,
                                               shape=(total_patches, n_bins, NSIDE_PATCH, NSIDE_PATCH))
        noise_out = np.lib.format.open_memmap(tmp_noise_file, mode="w+", dtype=np.float32,
                                               shape=(total_patches, NSIDE_PATCH, NSIDE_PATCH))
        T_out     = np.lib.format.open_memmap(tmp_T_file, mode="w+", dtype=np.float32,
                                               shape=(total_patches, NSIDE_PATCH, NSIDE_PATCH))

        source_n = find_source_cache_n(N_REALIZATIONS)
        if source_n is not None:
            source_base = patch_cache_filename_base_for(source_n)
            source_patches = source_n * n_patches_per_map
            print(f"Found existing complete cache for n={source_n} -- copying "
                  f"{source_patches} patches forward instead of reprocessing them")
            _copy_memmap_prefix(source_base + "_tau_stack.npy", tau_out, source_patches)
            _copy_memmap_prefix(source_base + "_v_target_stack.npy", v_out, source_patches)
            _copy_memmap_prefix(source_base + "_noise.npy", noise_out, source_patches)
            _copy_memmap_prefix(source_base + "_T.npy", T_out, source_patches)
            tau_out.flush(); v_out.flush(); noise_out.flush(); T_out.flush()
            start_i = source_n
            with open(progress_file, "w") as f:
                f.write(str(start_i))
            print(f"Copy-forward complete -- will process realizations {start_i}..{N_REALIZATIONS - 1} fresh")
        else:
            start_i = 0
            print(f"No smaller existing cache found -- building all {N_REALIZATIONS} realizations from scratch")

    for i in range(start_i, N_REALIZATIONS):
        s = slice(i * n_patches_per_map, (i + 1) * n_patches_per_map)

        for bi, b in enumerate(BIN_NAMES):
            v_ring = np.array(v_mmaps[b][i])
            v_nest = hp.reorder(v_ring, r2n=True)
            v_out[s, bi] = extract_all_patches_from_map(v_nest, NSIDE_MAP, NSIDE_PATCH)
            del v_ring, v_nest

            tau_ring = np.array(tau_mmaps[b][i])
            tau_nest = hp.reorder(tau_ring, r2n=True)
            tau_out[s, bi] = extract_all_patches_from_map(tau_nest, NSIDE_MAP, NSIDE_PATCH)
            del tau_ring, tau_nest

        noise_ring = np.array(noise_mmap[i])
        noise_nest = hp.reorder(noise_ring, r2n=True)
        noise_out[s] = extract_all_patches_from_map(noise_nest, NSIDE_MAP, NSIDE_PATCH)
        del noise_ring, noise_nest

        T_ring = np.array(T_mmap[i])
        T_nest = hp.reorder(T_ring, r2n=True)
        T_out[s] = extract_all_patches_from_map(T_nest, NSIDE_MAP, NSIDE_PATCH)
        del T_ring, T_nest

        tau_out.flush(); v_out.flush(); noise_out.flush(); T_out.flush()
        with open(progress_file, "w") as f:
            f.write(str(i + 1))

        gc.collect()
        print(f"Patched {i+1}/{N_REALIZATIONS} realizations — saved to disk")

    del v_mmaps, tau_mmaps, noise_mmap, T_mmap
    del tau_out, v_out, noise_out, T_out
    gc.collect()

    import shutil
    shutil.move(tmp_tau_file, final_tau_file)
    shutil.move(tmp_v_file, final_v_file)
    shutil.move(tmp_noise_file, final_noise_file)
    shutil.move(tmp_T_file, final_T_file)
    if os.path.exists(progress_file):
        os.remove(progress_file)

    print(f"Saved final files: {final_tau_file}, {final_v_file}, {final_noise_file}, {final_T_file}")
    return filename_base

def compute_stats_streaming(filepath, chunk_size=1000):
    # Mean/std over a large mmap'ed array without loading it all into memory at once.
    arr = np.load(filepath, mmap_mode="r")
    n = len(arr)
    total_sum = 0.0
    total_sq_sum = 0.0
    total_count = 0
    for i in range(0, n, chunk_size):
        chunk = np.array(arr[i:i+chunk_size], dtype=np.float64)
        total_sum += chunk.sum()
        total_sq_sum += (chunk**2).sum()
        total_count += chunk.size
    mean = total_sum / total_count
    var = total_sq_sum / total_count - mean**2
    std = np.sqrt(var)
    del arr
    return float(mean), float(std)

filename_base = build_and_save_stage_chunked_binned()
tau_stack_file = filename_base + "_tau_stack.npy"
v_target_stack_file = filename_base + "_v_target_stack.npy"
noise_file = filename_base + "_noise.npy"
T_file = filename_base + "_T.npy"

for label, path in [("tau_stack", tau_stack_file), ("v_target_stack", v_target_stack_file),
                     ("noise", noise_file), ("T", T_file)]:
    m, s = compute_stats_streaming(path)
    print(f"{label}: mean={m:.4f} std={s:.4f}")

##=====================================
##  LOAD LOSS WEIGHTS (from binned_loss_scale.npz -- shared across all 3 bins)
##=====================================
if not os.path.exists(LOSS_SCALE_FILE):
    raise FileNotFoundError(f"{LOSS_SCALE_FILE} not found — run the loss-weight notebook first.")

_scales = np.load(LOSS_SCALE_FILE)
weight_pixel    = float(_scales["weight_pixel"])
weight_patch    = float(_scales["weight_patch"])
weight_spectral = float(_scales["weight_spectral"])
N_SPEC_BINS   = int(_scales["n_spec_bins"])
SPEC_LOSS_EPS = float(_scales["spec_loss_eps"])
print(f"Loaded loss weights: weight_pixel={weight_pixel:.6e}, weight_patch={weight_patch:.6e}, "
      f"weight_spectral={weight_spectral:.6e}  (n_spec_bins={N_SPEC_BINS}, spec_loss_eps={SPEC_LOSS_EPS})")

##=====================================
##  DATASET CLASSES
##=====================================
class VTauNoiseDatasetFromDisk(Dataset):
    """
    Eps-agnostic. Stores tau_stack (n,3,H,W), v_target_stack (n,3,H,W),
    noise (n,H,W), T (n,H,W). Tnoise = T + eps*noise is composed on demand
    via get_raw(), same principle as the original single-shell version.
    """
    def __init__(self, tau_stack_file, v_target_stack_file, noise_file, T_file):
        self.tau_stack = np.load(tau_stack_file, mmap_mode="r")
        self.v_target_stack = np.load(v_target_stack_file, mmap_mode="r")
        self.noise = np.load(noise_file, mmap_mode="r")
        self.T = np.load(T_file, mmap_mode="r")

    def __len__(self):
        return len(self.T)

    def get_raw(self, idx):
        return (np.array(self.tau_stack[idx]), np.array(self.v_target_stack[idx]),
                np.array(self.noise[idx]), np.array(self.T[idx]))

class MixedEpsilonDataset(Dataset):
    """
    Same mixing/curriculum sampling mechanism as the original single-shell
    version. Tnoise = T + eps*noise is composed at __getitem__ time; input
    is [Tnoise, tau0, tau1, tau2] (4,H,W), target is [v0,v1,v2] (3,H,W).
    """
    def __init__(self, base_dataset, index_pool, eps_list, samples_per_epoch: int, seed=RUN_SEED):
        self.base_dataset = base_dataset
        self.index_pool = np.asarray(index_pool)
        self.eps_keys = list(eps_list)
        self.samples_per_epoch = samples_per_epoch
        self.rng = np.random.default_rng(seed)
        self.weights = None
        self._plan = None

    def set_weights(self, weights: dict):
        w = np.array([weights.get(k, 0.0) for k in self.eps_keys], dtype=np.float64)
        assert np.isclose(w.sum(), 1.0), f"weights sum to {w.sum()}, expected 1.0"
        self.weights = w

    def resample(self, samples_per_epoch=None):
        assert self.weights is not None, "call set_weights() before resample()"
        if samples_per_epoch is not None:
            self.samples_per_epoch = samples_per_epoch
        chosen_eps = self.rng.choice(self.eps_keys, size=self.samples_per_epoch, p=self.weights)
        chosen_idx = self.rng.choice(self.index_pool, size=self.samples_per_epoch, replace=True)
        self._plan = list(zip(chosen_eps, chosen_idx))

    def __len__(self):
        return self.samples_per_epoch

    def __getitem__(self, idx):
        eps, local_idx = self._plan[idx]
        tau3, v3, noise, T = self.base_dataset.get_raw(local_idx)
        Tnoise = (T + eps * noise).astype(np.float32)
        inp = torch.from_numpy(
            np.concatenate([Tnoise[None, :, :], tau3.astype(np.float32)], axis=0)
        )  # (4, H, W)
        target = torch.from_numpy(v3.astype(np.float32))  # (3, H, W)
        return inp, target, torch.tensor(eps, dtype=torch.float32)

TRAIN_IDX = np.concatenate([np.arange(r * n_patches_per_map, (r + 1) * n_patches_per_map) for r in TRAIN_REALIZATIONS])
VAL_IDX   = np.concatenate([np.arange(r * n_patches_per_map, (r + 1) * n_patches_per_map) for r in VAL_REALIZATIONS])

full_dataset = VTauNoiseDatasetFromDisk(tau_stack_file, v_target_stack_file, noise_file, T_file)
print(f"Built single eps-agnostic patch dataset, shared across eps values: {EPS_LIST}")

##=====================================
##  LOSS FUNCTIONS  (channel-averaged: flat mean over batch AND channel dims)
##=====================================
def pixel_loss_fn(pred, target):
    # pred, target: (B, 3, H, W) -- flat mean averages equally over channels
    return torch.mean((pred - target) ** 2)

def patch_loss_fn(pred, target):
    # pred, target: (B, 3, H, W)
    pred_mean   = pred.mean(dim=(2, 3))    # (B, 3)
    target_mean = target.mean(dim=(2, 3))  # (B, 3)
    return torch.mean((pred_mean - target_mean) ** 2)

_RADIAL_BIN_CACHE = {}

def get_radial_bins(patch_size, n_bins, torch_device):
    # Precompute (and cache) which log-spaced radial frequency bin each
    # (kx, ky) FFT frequency component falls into, for a given patch size.
    key = (patch_size, n_bins, str(torch_device))
    if key in _RADIAL_BIN_CACHE:
        return _RADIAL_BIN_CACHE[key]
    freqs_y = torch.fft.fftfreq(patch_size)
    freqs_x = torch.fft.rfftfreq(patch_size)
    ky, kx = torch.meshgrid(freqs_y, freqs_x, indexing='ij')
    k = torch.sqrt(kx**2 + ky**2)
    k_flat = k.flatten()
    nonzero = k_flat[k_flat > 0]
    kmin = nonzero.min()
    kmax = k_flat.max()
    bin_edges = torch.logspace(torch.log10(kmin), torch.log10(kmax), n_bins + 1)
    bin_idx = torch.bucketize(k_flat, bin_edges) - 1
    bin_idx = bin_idx.clamp(0, n_bins - 1).long().to(torch_device)
    _RADIAL_BIN_CACHE[key] = bin_idx
    return bin_idx

def radial_power_spectrum(patch_batch, n_bins=N_SPEC_BINS):
    # patch_batch: (N, H, W) -- N can be B*C (channels flattened into batch)
    # 2D FFT power spectrum of each patch, averaged into n_bins log-spaced
    # radial frequency bins (an isotropic power spectrum per patch).
    N, H, W = patch_batch.shape
    fft = torch.fft.rfft2(patch_batch)
    power = fft.real**2 + fft.imag**2
    bin_idx = get_radial_bins(H, n_bins, patch_batch.device)
    power_flat = power.reshape(N, -1)
    binned = torch.zeros(N, n_bins, device=patch_batch.device, dtype=power.dtype)
    binned.index_add_(1, bin_idx, power_flat)
    counts = torch.zeros(n_bins, device=patch_batch.device, dtype=power.dtype)
    counts.index_add_(0, bin_idx, torch.ones_like(bin_idx, dtype=power.dtype))
    counts = counts.clamp(min=1.0)
    binned = binned / counts.unsqueeze(0)
    return binned

def spectral_loss_fn(pred, target, n_bins=N_SPEC_BINS, eps=SPEC_LOSS_EPS):
    # pred, target: (B, 3, H, W) -- flatten channel into batch dim for the FFT,
    # then the final mean naturally averages over channels too
    B, C, H, W = pred.shape
    pred_flat   = pred.reshape(B * C, H, W)
    target_flat = target.reshape(B * C, H, W)

    P_pred = radial_power_spectrum(pred_flat, n_bins=n_bins)
    P_true = radial_power_spectrum(target_flat, n_bins=n_bins)

    log_pred = torch.log(P_pred + eps)
    log_true = torch.log(P_true + eps)

    return torch.mean((log_pred - log_true) ** 2)

def combined_loss_fn(pred, target):
    l_pixel = pixel_loss_fn(pred, target)
    l_patch = patch_loss_fn(pred, target)
    l_spectral = spectral_loss_fn(pred, target)
    total = weight_pixel * l_pixel + weight_patch * l_patch + weight_spectral * l_spectral
    return total, l_pixel.detach(), l_patch.detach(), l_spectral.detach()

print("Component losses ready: pixel MSE, patch-average MSE, spectral (log-space radial power) MSE — all channel-averaged")

##=====================================
##  ViT MODEL  (in_ch=4, out_ch=3; architecture otherwise unchanged)
##=====================================
class SimpleViT(nn.Module):
    def __init__(self, img_size, patch_size=8, in_ch=4, out_ch=3,
                 embed_dim=64, depth=4, n_heads=4, mlp_ratio=4, eps_max=EPS_MAX):
        super().__init__()
        assert img_size % patch_size == 0
        self.img_size = img_size
        self.patch_size = patch_size
        self.grid = img_size // patch_size
        self.n_tokens = self.grid * self.grid
        self.out_ch = out_ch
        self.eps_max = eps_max
        self.patch_embed = nn.Conv2d(in_ch, embed_dim, kernel_size=patch_size, stride=patch_size)
        self.pos_embed = nn.Parameter(torch.randn(1, self.n_tokens, embed_dim) * 0.02)
        self.eps_embed = nn.Sequential(
            nn.Linear(1, embed_dim),
            nn.GELU(),
            nn.Linear(embed_dim, embed_dim),
        )
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim, nhead=n_heads, dim_feedforward=embed_dim * mlp_ratio,
            batch_first=True, activation='gelu'
        )
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=depth)
        self.norm = nn.LayerNorm(embed_dim)
        self.head = nn.Linear(embed_dim, out_ch * patch_size * patch_size)

    def forward(self, x, eps):
        # Patchify -> add positional + eps-conditioning embeddings ->
        # transformer encoder -> per-token linear head -> reassemble tokens
        # back into a full (out_ch, img_size, img_size) prediction.
        B, C, H, W = x.shape
        tokens = self.patch_embed(x)
        tokens = tokens.flatten(2).transpose(1, 2)
        tokens = tokens + self.pos_embed

        eps_norm = (eps.float() / self.eps_max).view(B, 1)
        eps_emb = self.eps_embed(eps_norm)
        tokens = tokens + eps_emb.unsqueeze(1)

        tokens = self.encoder(tokens)
        tokens = self.norm(tokens)
        out = self.head(tokens)
        p = self.patch_size
        out = out.reshape(B, self.grid, self.grid, self.out_ch, p, p)
        out = out.permute(0, 3, 1, 4, 2, 5)
        out = out.reshape(B, self.out_ch, self.grid * p, self.grid * p)
        return out

##=====================================
##  CURRICULUM STAGES  (two-tier retirement: TIER1 [new intermediates] gives
##  up weight first; TIER2 [original odd values] only starts giving up weight
##  once every currently-active TIER1 member is already at its floor. Both
##  tiers keep a permanent RETIRE_FLOOR weight once introduced -- they are
##  never fully zeroed out, so eps_embed keeps getting supervision everywhere.)
##=====================================
def compute_stage_weights(active, tier1_set, tier2_set, prev_weights, eps0_weight,
                           base_weight=0.12, retire_floor=0.02):
    # Given the eps=0 weight for this stage, redistribute the remaining
    # budget across the currently-active nonzero eps values: tier1 values
    # get trimmed toward retire_floor first, then tier2 (only once every
    # tier1 member is already floored), then any leftover deficit is spread
    # evenly across the "durable" (non-retiring) values. A surplus
    # (deficit < 0) is instead added evenly to whichever pool is available.
    remaining_budget = 1.0 - eps0_weight
    durable = [e for e in active if e not in tier1_set and e not in tier2_set]
    tier1   = [e for e in active if e in tier1_set]
    tier2   = [e for e in active if e in tier2_set]

    weights = {e: prev_weights.get(e, base_weight) for e in active}
    deficit = sum(weights.values()) - remaining_budget

    if deficit > 1e-9:
        for e in tier1:
            if deficit <= 1e-9:
                break
            take = min(weights[e] - retire_floor, deficit)
            if take > 0:
                weights[e] -= take
                deficit -= take
        tier1_floored = all(weights[e] <= retire_floor + 1e-9 for e in tier1) if tier1 else True
        if tier1_floored:
            for e in tier2:
                if deficit <= 1e-9:
                    break
                take = min(weights[e] - retire_floor, deficit)
                if take > 0:
                    weights[e] -= take
                    deficit -= take
        if deficit > 1e-9 and durable:
            per = deficit / len(durable)
            for e in durable:
                weights[e] = max(0.0, weights[e] - per)
    elif deficit < -1e-9:
        surplus = -deficit
        pool = durable if durable else (tier1 if tier1 else tier2)
        if pool:
            per = surplus / len(pool)
            for e in pool:
                weights[e] += per

    return weights

def build_curriculum_stages(eps_list, samples_per_eps, eps0_start=1.0, eps0_end=0.3,
                             base_weight=0.12, retire_floor=0.02):
    # Build the full stage-by-stage weight schedule: one new eps value
    # activated per stage (stage 1 = eps=0 only), with eps=0's share
    # linearly ramped down from eps0_start to eps0_end across the stages
    # and the rest of the budget distributed via compute_stage_weights.
    nonzero_eps = eps_list[1:]
    n_stages = len(eps_list)

    active = []
    prev_weights = {}
    stages = [{"weights": {0.0: 1.0}, "samples_per_epoch": samples_per_eps}]

    for stage_i in range(2, n_stages + 1):
        new_eps = nonzero_eps[stage_i - 2]
        active.append(new_eps)

        eps0_weight = eps0_start - (eps0_start - eps0_end) * (stage_i - 1) / (n_stages - 1)
        nonzero_weights = compute_stage_weights(active, TIER1_RETIRE, TIER2_RETIRE, prev_weights,
                                                  eps0_weight, base_weight=base_weight, retire_floor=retire_floor)

        weights = {0.0: eps0_weight, **nonzero_weights}
        total = sum(weights.values())
        weights = {k: v / total for k, v in weights.items()}

        stages.append({"weights": weights, "samples_per_epoch": samples_per_eps * len(weights)})
        prev_weights = nonzero_weights

    return stages

# One full pass over the currently available train patches, per eps value,
# per stage -- derived from TRAIN_REALIZATIONS/n_patches_per_map so this
# scales automatically the next time N_REALIZATIONS grows, instead of
# silently under- or over-sampling relative to a stale hardcoded constant.
SAMPLES_PER_EPS = len(TRAIN_REALIZATIONS) * n_patches_per_map
print(f"SAMPLES_PER_EPS={SAMPLES_PER_EPS} (derived from {len(TRAIN_REALIZATIONS)} train "
      f"realizations x {n_patches_per_map} patches/map)")

CURRICULUM_STAGES = build_curriculum_stages(EPS_LIST, samples_per_eps=SAMPLES_PER_EPS)

for _i, _stage in enumerate(CURRICULUM_STAGES):
    _s = sum(_stage["weights"].values())
    assert np.isclose(_s, 1.0), f"CURRICULUM_STAGES[{_i}] weights sum to {_s}, expected 1.0: {_stage['weights']}"
print(f"All {len(CURRICULUM_STAGES)} curriculum stages have weights summing to 1.0 -- OK")
for _i, _stage in enumerate(CURRICULUM_STAGES):
    print(f"  Stage {_i+1:2d} [{len(_stage['weights']):2d} active, "
          f"samples/epoch={_stage['samples_per_epoch']:7,d}]: "
          f"{ {k: round(v,4) for k,v in sorted(_stage['weights'].items())} }")

# --- easily-editable hyperparameters ---
PATIENCE     = 10
MIN_DELTA    = 0.0005
VAL_FRACTION = 0.15 # fraction of each stage's samples used for validation
BATCH_SIZE   = 256
MAX_EPOCHS   = 1000
GRAD_CLIP_MAX_NORM = 1.0
LEARNING_RATE = 1e-3
SAFETY_CHECKPOINT_EVERY = 5

##=====================================
##  MOLLWEIDE TRUE-VS-RECONSTRUCTED-VS-RESIDUAL COMPARISON  (per bin)
##=====================================
def plot_mollweide_multi(v_true_ring, recon_rings: dict, label=None, filename_tag=None):
    eps_list = sorted(recon_rings.keys())
    n_cols = 1 + len(eps_list)
    fig = plt.figure(figsize=(5 * n_cols, 10))
    vmax = np.nanpercentile(np.abs(v_true_ring), 99)

    hp.mollview(v_true_ring, fig=fig, sub=(2, n_cols, 1),
                title="True v", min=-vmax, max=vmax, cmap="RdBu_r")

    for i, eps in enumerate(eps_list):
        recon_ring = recon_rings[eps]
        col = i + 2
        hp.mollview(recon_ring, fig=fig, sub=(2, n_cols, col),
                    title=f"Reconstructed (eps={eps})", min=-vmax, max=vmax, cmap="RdBu_r")
        residual = v_true_ring - recon_ring
        res_vmax = np.nanpercentile(np.abs(residual), 99)
        hp.mollview(residual, fig=fig, sub=(2, n_cols, n_cols + col),
                    title=f"Residual (eps={eps})", min=-res_vmax, max=res_vmax, cmap="RdBu_r")

    suptitle = "Mollweide comparison across epsilons" + (f" — {label}" if label else "")
    fig.suptitle(suptitle, y=1.02)
    plt.tight_layout()
    tag_str = f"_{filename_tag}" if filename_tag else ""
    fname = f"mollweide_multi_epoch{label.replace(' ', '_').replace(',', '') if label else 'unlabeled'}{tag_str}.png"
    fig_path = os.path.join(DATA_DIR, fname)
    plt.savefig(fig_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved multi-epsilon Mollweide comparison to {fig_path}")

##=====================================
##  PATCH TRUE-VS-RECONSTRUCTED COMPARISON  (per bin)
##=====================================
PATCH_COMPARISON_LOCATIONS = [
    {"face": 0,  "row": 0, "col": 0},
    {"face": 5,  "row": 4, "col": 4},
]

def extract_all_patches(map_nest, nside_map, nside_patch, face_idx=FACE_IDX):
    all_patches = []
    for face_id in range(12):
        face_img = get_face_2d(map_nest, nside_map, face_id, face_idx)
        n_per_side = nside_map // nside_patch
        for pr in range(n_per_side):
            for pc in range(n_per_side):
                patch = face_img[pr*nside_patch:(pr+1)*nside_patch, pc*nside_patch:(pc+1)*nside_patch]
                all_patches.append({"face": face_id, "row": pr, "col": pc, "data": patch})
    return all_patches

def plot_patch_multi(v_true_nest, recon_nests: dict, label=None, filename_tag=None,
                      locations=PATCH_COMPARISON_LOCATIONS):
    eps_list = sorted(recon_nests.keys())
    n_cols = 1 + len(eps_list)
    n_rows = len(locations)

    true_patches = extract_all_patches(v_true_nest, NSIDE_MAP, NSIDE_PATCH, FACE_IDX)
    true_lookup = {(p["face"], p["row"], p["col"]): p["data"] for p in true_patches}

    recon_lookups = {}
    for eps, recon_nest in recon_nests.items():
        recon_patches = extract_all_patches(recon_nest, NSIDE_MAP, NSIDE_PATCH, FACE_IDX)
        recon_lookups[eps] = {(p["face"], p["row"], p["col"]): p["data"] for p in recon_patches}

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(5 * n_cols, 5 * n_rows))
    axes = np.array(axes).reshape(n_rows, n_cols)

    for row, loc in enumerate(locations):
        key = (loc["face"], loc["row"], loc["col"])
        true_patch = true_lookup[key]
        vmax = np.nanpercentile(np.abs(true_patch), 99)

        axes[row, 0].imshow(true_patch, cmap="RdBu_r", vmin=-vmax, vmax=vmax, interpolation="nearest")
        axes[row, 0].set_title(f"true (face={key[0]},row={key[1]},col={key[2]})", fontsize=9)
        axes[row, 0].set_xticks([]); axes[row, 0].set_yticks([])

        for col, eps in enumerate(eps_list, start=1):
            pred_patch = recon_lookups[eps][key]
            mse = float(np.mean((pred_patch - true_patch) ** 2))
            axes[row, col].imshow(pred_patch, cmap="RdBu_r", vmin=-vmax, vmax=vmax, interpolation="nearest")
            axes[row, col].set_title(f"eps={eps} (MSE={mse:.3e})", fontsize=9)
            axes[row, col].set_xticks([]); axes[row, col].set_yticks([])

    suptitle = "Patch comparison across epsilons" + (f" — {label}" if label else "")
    fig.suptitle(suptitle, y=1.0)
    plt.tight_layout()
    tag_str = f"_{filename_tag}" if filename_tag else ""
    fname = f"patchcompare_multi_epoch{label.replace(' ', '_').replace(',', '') if label else 'unlabeled'}{tag_str}.png"
    fig_path = os.path.join(DATA_DIR, fname)
    plt.savefig(fig_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved multi-epsilon patch comparison to {fig_path}")

##=====================================
##  TEST SNAPSHOT  (one Mollweide + one patch-comparison set PER BIN)
##=====================================
def test_snapshot(model, eps_to_test: list, label=None, filename_tag=None):
    v_test_rings   = {b: np.load(TEST_FILES[f"v{b}"]) for b in BIN_NAMES}
    tau_test_rings = {b: np.load(TEST_FILES[f"tau{b}"]) for b in BIN_NAMES}
    noise_test_ring = np.load(TEST_FILES["cmbnoise"])
    T_test_ring = np.load(TEST_FILES["T"])

    tau_test_nests = {b: hp.reorder(tau_test_rings[b], r2n=True) for b in BIN_NAMES}
    v_test_nests   = {b: hp.reorder(v_test_rings[b], r2n=True) for b in BIN_NAMES}

    Cl_true = {b: hp.anafast(v_test_rings[b], lmax=LMAX) for b in BIN_NAMES}

    model.eval()
    Cl_preds = {b: {} for b in BIN_NAMES}
    recon_rings = {b: {} for b in BIN_NAMES}
    recon_nests = {b: {} for b in BIN_NAMES}

    for eps in eps_to_test:
        Tnoise_test_ring = (T_test_ring + eps * noise_test_ring).astype(np.float32)
        Tnoise_test_nest = hp.reorder(Tnoise_test_ring, r2n=True)

        tau_maps_nest = [tau_test_nests[b] for b in BIN_NAMES]
        recon_nests_list = reconstruct_full_maps_multi(
            model, Tnoise_test_nest, tau_maps_nest, NSIDE_MAP, NSIDE_PATCH, eps=eps
        )

        for bi, b in enumerate(BIN_NAMES):
            recon_nest = recon_nests_list[bi]
            recon_ring = hp.reorder(recon_nest, n2r=True)
            Cl_preds[b][eps] = hp.anafast(recon_ring, lmax=LMAX)
            recon_rings[b][eps] = recon_ring
            recon_nests[b][eps] = recon_nest

        del Tnoise_test_ring, Tnoise_test_nest
        gc.collect()

    for b in BIN_NAMES:
        bin_tag = f"{filename_tag}_bin{b}" if filename_tag else f"bin{b}"
        plot_mollweide_multi(v_test_rings[b], recon_rings[b], label=label, filename_tag=bin_tag)
        plot_patch_multi(v_test_nests[b], recon_nests[b], label=label, filename_tag=bin_tag)

        fig, ax = plt.subplots(figsize=(9, 6))
        ax.plot(Cl_true[b], color='black', linewidth=2, label="true")
        for eps in eps_to_test:
            ax.plot(Cl_preds[b][eps], label=f"eps={eps}", alpha=0.8)
        ax.set_xscale('log'); ax.set_yscale('log')
        ax.set_ylim(1e-7, None)
        ax.set_xlabel(r"$\ell$")
        ax.set_ylabel(r"$C_\ell$")
        ax.legend()
        title = f"Reconstruction quality — bin {b}" + (f" — {label}" if label else "")
        ax.set_title(title)
        plt.tight_layout()
        tag_str = f"_{bin_tag}"
        fig_path = os.path.join(DATA_DIR, f"snapshot_epoch{label.replace(' ', '_').replace(',', '') if label else 'unlabeled'}{tag_str}.png")
        plt.savefig(fig_path, dpi=150)
        plt.close(fig)
        print(f"Saved snapshot plot to {fig_path}")

    del v_test_rings, tau_test_rings, noise_test_ring, T_test_ring
    del v_test_nests, tau_test_nests, recon_rings, recon_nests
    gc.collect()

    return Cl_true, Cl_preds

SNAPSHOT_ANCHORS = [0.05, 0.1, 0.2, 0.4, 0.6, 0.8, 1.0]

def select_snapshot_eps(eps_seen_so_far, stage_idx, eps_list, anchors=SNAPSHOT_ANCHORS):
    """
    Builds the eps set shown in a snapshot's Mollweide/patch/Cl plots:
      - eps=0.0 (noise-free case), always included
      - the eps introduced at this stage (stage_idx, 0-indexed into eps_list)
      - the eps introduced at the previous stage
      - any anchor value (0.05, 0.1, 0.2, 0.4, 0.6, 0.8, 1.0) already seen so far
    Keeps snapshot plots a small, fixed, readable width regardless of how many
    eps values the curriculum has accumulated by this point.
    """
    selected = {0.0}
    if stage_idx >= 1:
        selected.add(eps_list[stage_idx])       # most recently introduced
    if stage_idx >= 2:
        selected.add(eps_list[stage_idx - 1])    # previously introduced
    for a in anchors:
        if a in eps_seen_so_far:
            selected.add(a)
    return sorted(selected)

##=====================================
##  RESUME STATE
##=====================================
RESUME_STATE_FILE = os.path.join(DATA_DIR, f"resume_state_{SNAPSHOT_TAG}.npz")

def save_resume_state(next_epoch, stage_idx, prev_stage_idx, epochs_since_improvement, best_val_loss,
                       global_best_val_loss, global_best_epoch, eps_seen_so_far, stage_log):
    # Persist everything needed to resume training exactly where it left
    # off after a restart: epoch/stage counters, early-stopping counters,
    # best-loss bookkeeping, which eps values have been introduced so far,
    # and the stage-transition log. None values are stored as -1 since npz
    # can't hold None.
    np.savez(RESUME_STATE_FILE,
             next_epoch=next_epoch,
             stage_idx=stage_idx,
             prev_stage_idx=prev_stage_idx if prev_stage_idx is not None else -1,
             epochs_since_improvement=epochs_since_improvement,
             best_val_loss=best_val_loss,
             global_best_val_loss=global_best_val_loss,
             global_best_epoch=global_best_epoch if global_best_epoch is not None else -1,
             eps_seen_so_far=np.array(sorted(eps_seen_so_far)),
             stage_log=np.array(stage_log, dtype=object))

def load_resume_state():
    if not os.path.exists(RESUME_STATE_FILE):
        return None
    d = np.load(RESUME_STATE_FILE, allow_pickle=True)
    gbe = int(d["global_best_epoch"])
    psi = int(d["prev_stage_idx"]) if "prev_stage_idx" in d else int(d["stage_idx"])
    return {
        "next_epoch": int(d["next_epoch"]),
        "stage_idx": int(d["stage_idx"]),
        "prev_stage_idx": None if psi == -1 else psi,
        "epochs_since_improvement": int(d["epochs_since_improvement"]),
        "best_val_loss": float(d["best_val_loss"]),
        "global_best_val_loss": float(d["global_best_val_loss"]),
        "global_best_epoch": None if gbe == -1 else gbe,
        "eps_seen_so_far": set(d["eps_seen_so_far"].tolist()),
        "stage_log": list(d["stage_log"]),
    }

##=====================================
##  TRAINING LOOP  (starts from scratch; resumable if interrupted)
##=====================================
CHECKPOINT_FILE      = os.path.join(DATA_DIR, f"model_weights_{SNAPSHOT_TAG}.pt")
BEST_CHECKPOINT_FILE = os.path.join(DATA_DIR, f"model_weights_{SNAPSHOT_TAG}_best.pt")
STAGE_BEST_CHECKPOINT_FILE = os.path.join(DATA_DIR, f"model_weights_{SNAPSHOT_TAG}_stage_best.pt")
TRAIN_HISTORY_FILE   = os.path.join(DATA_DIR, f"train_history_{SNAPSHOT_TAG}.npz")

# Set to True to ignore any existing checkpoint/history/resume-state files
# and force a fresh start from epoch 1, stage 1 -- saving still happens
# normally (and will overwrite whatever's currently on disk under this
# SNAPSHOT_TAG going forward). Set back to False for a normal resumable run.
FORCE_RESTART = os.environ.get("FORCE_RESTART", "0") == "1"
if FORCE_RESTART:
    print("FORCE_RESTART is set -- ignoring any existing checkpoint/history/resume-state "
          "files and starting fresh from epoch 1, stage 1. Saving proceeds normally from here.")

model = SimpleViT(img_size=NSIDE_PATCH, in_ch=4, out_ch=3, eps_max=EPS_MAX,
                   embed_dim=128, depth=5).to(device)

if not FORCE_RESTART and os.path.exists(CHECKPOINT_FILE):
    model.load_state_dict(torch.load(CHECKPOINT_FILE, map_location=device))
    model = model.to(device)
    print(f"Resumed model weights from {CHECKPOINT_FILE}")
else:
    print("No checkpoint found — starting fresh from random initialization (no warm-start)")

optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
print(f"Using COMBINED patch + spectral loss (channel-averaged, normalized weighted sum), "
      f"FULL {len(CURRICULUM_STAGES)}-STAGE NOISE CURRICULUM (eps up to {EPS_MAX}), "
      f"batch_size={BATCH_SIZE}, grad_clip_max_norm={GRAD_CLIP_MAX_NORM}")

_active_train_subsets = (full_dataset, TRAIN_IDX)
_active_val_subsets   = (full_dataset, VAL_IDX)

train_losses, val_losses = [], []
train_losses_pixel, train_losses_patch, train_losses_spectral = [], [], []
val_losses_pixel, val_losses_patch, val_losses_spectral = [], [], []

if not FORCE_RESTART and os.path.exists(TRAIN_HISTORY_FILE):
    _prev_hist = np.load(TRAIN_HISTORY_FILE)
    train_losses           = list(_prev_hist["train_losses"])
    val_losses              = list(_prev_hist["val_losses"])
    train_losses_pixel      = list(_prev_hist["train_losses_pixel"])
    train_losses_patch      = list(_prev_hist["train_losses_patch"])
    train_losses_spectral   = list(_prev_hist["train_losses_spectral"])
    val_losses_pixel         = list(_prev_hist["val_losses_pixel"])
    val_losses_patch         = list(_prev_hist["val_losses_patch"])
    val_losses_spectral      = list(_prev_hist["val_losses_spectral"])
    print(f"Loaded {len(train_losses)} epochs of prior loss history from {TRAIN_HISTORY_FILE} -- will extend, not overwrite")

resume_state = None if FORCE_RESTART else load_resume_state()
train_mixed_ds = MixedEpsilonDataset(*_active_train_subsets, EPS_LIST, samples_per_epoch=CURRICULUM_STAGES[0]["samples_per_epoch"], seed=RUN_SEED)
val_mixed_ds = None

if resume_state is not None:
    start_epoch               = resume_state["next_epoch"]
    stage_idx                 = resume_state["stage_idx"]
    prev_stage_idx             = resume_state["prev_stage_idx"]
    epochs_since_improvement   = resume_state["epochs_since_improvement"]
    best_val_loss              = resume_state["best_val_loss"]
    global_best_val_loss       = resume_state["global_best_val_loss"]
    global_best_epoch          = resume_state["global_best_epoch"]
    eps_seen_so_far            = resume_state["eps_seen_so_far"]
    stage_log                  = resume_state["stage_log"]

    print(f"Resuming curriculum: next epoch={start_epoch+1}, stage={stage_idx+1}/{len(CURRICULUM_STAGES)}, "
          f"epochs_since_improvement={epochs_since_improvement}, stage best_val_loss={best_val_loss}, "
          f"global_best_val_loss={global_best_val_loss}, global_best_epoch={global_best_epoch}")

    _stage = CURRICULUM_STAGES[stage_idx]
    train_mixed_ds.set_weights(_stage["weights"])
    _val_samples = max(1, int(_stage["samples_per_epoch"] * VAL_FRACTION))
    val_mixed_ds = MixedEpsilonDataset(*_active_val_subsets, EPS_LIST, samples_per_epoch=_val_samples, seed=RUN_SEED + 1000 + start_epoch)
    val_mixed_ds.set_weights(_stage["weights"])
    val_mixed_ds.resample()
else:
    start_epoch               = 0
    stage_idx                 = 0
    prev_stage_idx             = None
    epochs_since_improvement   = 0
    best_val_loss              = float("inf")
    global_best_val_loss       = float("inf")
    global_best_epoch          = None
    eps_seen_so_far            = set()
    stage_log                  = []
    print("No resume state found — starting fresh from stage 1, epoch 1")

def save_all_checkpoints(final=False):
    torch.save(model.state_dict(), CHECKPOINT_FILE)
    np.savez(TRAIN_HISTORY_FILE,
             train_losses=np.array(train_losses),
             val_losses=np.array(val_losses),
             train_losses_pixel=np.array(train_losses_pixel),
             train_losses_patch=np.array(train_losses_patch),
             train_losses_spectral=np.array(train_losses_spectral),
             val_losses_pixel=np.array(val_losses_pixel),
             val_losses_patch=np.array(val_losses_patch),
             val_losses_spectral=np.array(val_losses_spectral),
             weight_pixel=weight_pixel,
             weight_patch=weight_patch,
             weight_spectral=weight_spectral,
             best_val_loss=global_best_val_loss,
             best_epoch=global_best_epoch)

for epoch in range(start_epoch, MAX_EPOCHS):
    stage = CURRICULUM_STAGES[stage_idx]

    # --- stage transition: runs once, the epoch right after stage_idx changed ---
    # (triggered below by "epochs_since_improvement >= PATIENCE" incrementing
    # stage_idx at the end of the previous iteration). Snapshots + checkpoints
    # the just-finished stage, then rebuilds the train/val mixture for the new
    # one and resets the early-stopping counters.
    if stage_idx != prev_stage_idx:
        if prev_stage_idx is not None:
            stage_end_ckpt = os.path.join(DATA_DIR, f"model_weights_{SNAPSHOT_TAG}_stage{prev_stage_idx+1}_end.pt")
            torch.save(model.state_dict(), stage_end_ckpt)
            print(f"Saved end-of-stage-{prev_stage_idx+1} checkpoint to {stage_end_ckpt}")

            print(f"\n--- Progress snapshot before advancing from stage {prev_stage_idx+1} "
                  f"to stage {stage_idx+1} (epoch {epoch}) ---")
            test_snapshot(
                model,
                eps_to_test=select_snapshot_eps(eps_seen_so_far, prev_stage_idx, EPS_LIST),
                label=f"epoch {epoch}, end of stage {prev_stage_idx+1}",
                filename_tag=SNAPSHOT_TAG
            )

        print(f"\n=== CURRICULUM UPDATE at epoch {epoch} (stage {stage_idx+1}/{len(CURRICULUM_STAGES)}) ===")
        print(f"New epsilon weights: {stage['weights']}")
        if prev_stage_idx is not None:
            print(f"(previously: {CURRICULUM_STAGES[prev_stage_idx]['weights']})")
        print(f"Samples per epoch (train): {stage['samples_per_epoch']}")

        train_mixed_ds.set_weights(stage["weights"])

        val_samples = max(1, int(stage["samples_per_epoch"] * VAL_FRACTION))
        val_mixed_ds = MixedEpsilonDataset(*_active_val_subsets, EPS_LIST, samples_per_epoch=val_samples, seed=RUN_SEED + 1000 + epoch)
        val_mixed_ds.set_weights(stage["weights"])
        val_mixed_ds.resample()
        print(f"Validation set rebuilt to match new mixture ({val_samples} samples).")

        eps_seen_so_far |= set(stage["weights"].keys())
        stage_log.append((epoch, stage_idx, dict(stage["weights"])))
        prev_stage_idx = stage_idx
        epochs_since_improvement = 0
        best_val_loss = float("inf")

    train_mixed_ds.resample(stage["samples_per_epoch"])
    train_loader = DataLoader(
        train_mixed_ds, batch_size=BATCH_SIZE, shuffle=True, pin_memory=True,
        num_workers=NUM_WORKERS, prefetch_factor=PREFETCH_FACTOR,
    )
    val_loader = DataLoader(
        val_mixed_ds, batch_size=BATCH_SIZE, pin_memory=True,
        num_workers=NUM_WORKERS, prefetch_factor=PREFETCH_FACTOR,
    )

    n_train = len(train_mixed_ds)
    n_val   = len(val_mixed_ds)

    model.train()
    epoch_loss = epoch_loss_pixel = epoch_loss_patch = epoch_loss_spectral = 0.0
    for inp, target, eps_batch in train_loader:
        inp, target, eps_batch = inp.to(device), target.to(device), eps_batch.to(device)
        optimizer.zero_grad()
        pred = model(inp, eps_batch)
        loss, l_pixel, l_patch, l_spectral = combined_loss_fn(pred, target)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=GRAD_CLIP_MAX_NORM)
        optimizer.step()
        epoch_loss += loss.item() * inp.size(0)
        epoch_loss_pixel += l_pixel.item() * inp.size(0)
        epoch_loss_patch += l_patch.item() * inp.size(0)
        epoch_loss_spectral += l_spectral.item() * inp.size(0)
    epoch_loss /= n_train
    epoch_loss_pixel /= n_train
    epoch_loss_patch /= n_train
    epoch_loss_spectral /= n_train
    train_losses.append(epoch_loss)
    train_losses_pixel.append(epoch_loss_pixel)
    train_losses_patch.append(epoch_loss_patch)
    train_losses_spectral.append(epoch_loss_spectral)

    model.eval()
    val_loss = val_loss_pixel = val_loss_patch = val_loss_spectral = 0.0
    with torch.no_grad():
        for inp, target, eps_batch in val_loader:
            inp, target, eps_batch = inp.to(device), target.to(device), eps_batch.to(device)
            pred = model(inp, eps_batch)
            loss, l_pixel, l_patch, l_spectral = combined_loss_fn(pred, target)
            val_loss += loss.item() * inp.size(0)
            val_loss_pixel += l_pixel.item() * inp.size(0)
            val_loss_patch += l_patch.item() * inp.size(0)
            val_loss_spectral += l_spectral.item() * inp.size(0)
    val_loss /= n_val
    val_loss_pixel /= n_val
    val_loss_patch /= n_val
    val_loss_spectral /= n_val
    val_losses.append(val_loss)
    val_losses_pixel.append(val_loss_pixel)
    val_losses_patch.append(val_loss_patch)
    val_losses_spectral.append(val_loss_spectral)

    print(f"Epoch {epoch+1}  (stage {stage_idx+1}/{len(CURRICULUM_STAGES)})  "
          f"train_total={epoch_loss:.5f}  val_total={val_loss:.5f}  |  "
          f"train[pixel={epoch_loss_pixel:.5f} patch={epoch_loss_patch:.5f} spectral={epoch_loss_spectral:.5f}]  "
          f"val[pixel={val_loss_pixel:.5f} patch={val_loss_patch:.5f} spectral={val_loss_spectral:.5f}]")

    if val_loss < global_best_val_loss:
        global_best_val_loss = val_loss
        global_best_epoch = epoch + 1
        torch.save(model.state_dict(), BEST_CHECKPOINT_FILE)
        print(f"  (new best combined val_loss={val_loss:.5f} at epoch {epoch+1} — saved to {BEST_CHECKPOINT_FILE})")

    if best_val_loss == float("inf"):
        relative_improvement = 1.0
    else:
        relative_improvement = (best_val_loss - val_loss) / best_val_loss

    if relative_improvement > MIN_DELTA:
        best_val_loss = val_loss
        epochs_since_improvement = 0
        torch.save(model.state_dict(), STAGE_BEST_CHECKPOINT_FILE)
    else:
        epochs_since_improvement += 1

    stage_finished = False
    if epochs_since_improvement >= PATIENCE:
        # Plateaued on this stage: roll back to the stage's own best
        # checkpoint (not the global best) before advancing, so the next
        # stage always starts from its predecessor's best weights rather
        # than whatever the last (possibly worse) epoch produced.
        if stage_idx < len(CURRICULUM_STAGES) - 1:
            if os.path.exists(STAGE_BEST_CHECKPOINT_FILE):
                model.load_state_dict(torch.load(STAGE_BEST_CHECKPOINT_FILE, map_location=device))
                print(f"  Rolled back to stage {stage_idx+1}'s best checkpoint "
                      f"(val_loss={best_val_loss:.5f}) before advancing to stage {stage_idx+2}")
            stage_idx += 1
        else:
            stage_finished = True

    save_resume_state(
        next_epoch=epoch + 1,
        stage_idx=stage_idx,
        prev_stage_idx=prev_stage_idx,
        epochs_since_improvement=epochs_since_improvement,
        best_val_loss=best_val_loss,
        global_best_val_loss=global_best_val_loss,
        global_best_epoch=global_best_epoch,
        eps_seen_so_far=eps_seen_so_far,
        stage_log=stage_log,
    )

    if stage_finished:
        print(f"\n=== TRAINING COMPLETE: final stage (stage {stage_idx+1}/{len(CURRICULUM_STAGES)}) "
              f"plateaued at epoch {epoch+1} — stopping automatically ===")
        save_all_checkpoints(final=True)
        break

    # Save every epoch, in lockstep with save_resume_state() above -- these
    # two MUST stay at the same frequency, or a resume can silently reload
    # stale model weights/history while the resume counters (epoch/stage/
    # patience) have already moved past that point. SAFETY_CHECKPOINT_EVERY
    # is kept only as a label for the printed message below, not as a
    # skip-interval -- do not reintroduce a "% SAFETY_CHECKPOINT_EVERY" gate
    # here without also gating save_resume_state() identically.
    save_all_checkpoints()
    if (epoch + 1) % SAFETY_CHECKPOINT_EVERY == 0:
        print(f"  (checkpoint + resume state saved at epoch {epoch+1})")

save_all_checkpoints()
print(f"Saved {CHECKPOINT_FILE} and {TRAIN_HISTORY_FILE}")
print(f"Best checkpoint: epoch {global_best_epoch}, val_loss={global_best_val_loss:.5f} -> {BEST_CHECKPOINT_FILE}")

del train_loader, val_loader
gc.collect()

print("\n--- Final snapshot across all eps values ---")
test_snapshot(model, eps_to_test=select_snapshot_eps(eps_seen_so_far, stage_idx, EPS_LIST),
              label="final full sweep", filename_tag=SNAPSHOT_TAG)